### ISSUE TITLE
Feature: Set start time on day plan

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#1002]
**What is the work that needs to be done?**

## Pass a startTime into the timestamper web component

1. Set startTime on hugo.toml in custom params so orgs can set a general rule
2. Allow day plan to override this front matter so specific sessions can be scheduled at other starts
3. Fallback to 10am if no start Time is present
4. Update https://common.codeyourfuture.io/common-theme/pages/day-plan/ with the new feature
https://github.com/CodeYourFuture/curriculum/blob/main/common-docs/content/common-theme/pages/day-plan.md?plain=1

https://github.com/CodeYourFuture/curriculum/blob/874907ac6f636e00e745ae1b79c6c429957e0eef/common-theme/assets/scripts/time-stamper.js#L20

https://github.com/CodeYourFuture/curriculum/blob/874907ac6f636e00e745ae1b79c6c429957e0eef/common-theme/hugo.toml#L28 

https://github.com/CodeYourFuture/curriculum/blob/874907ac6f636e00e745ae1b79c6c429957e0eef/common-theme/layouts/_default/day-plan.html#L30

**Why is this work important to do?**

At the moment the timestamp web component is hardcoded to start at 10am. We do start main courses at 10am, but ITD sessions might start at other times. And other orgs might want to start at a different time!

**Comment by gustavogabaldon** [comment]
hi, id like to contribute to this issue!

**Comment by SallyMcGrath** [comment]
🎉 Great - I'll assign you. Let me know if/when you have questions. Welcome to CYF 🤝

**Comment by 40thieves** [comment]
Hi @gustavogabaldon, have you managed to make progress on this ticket? We'd love to see a draft PR! 🙂
