### ISSUE TITLE
Simplify Coursework Planner instructions / Remove Kamino mentions

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#1018]
Just following these instructions again now - think we can simplify a bit.
https://programming.codeyourfuture.io/user-data/prep/#set-up-planner
And more importantly remove mentions of Kamino. I don't believe we need to use it at all any more as we have the magic `Clone` button next to each issue in the backlog page.

**Comment by illicitonion** [comment]
Ooh I totally have a PR out for this! https://github.com/CodeYourFuture/My-Coursework-Planner/pull/8
