### ISSUE TITLE
Step 4: give a code review/receive a code review as an A/C

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/curriculum#1055]
**Description**:
Suggestion from the Retro: In Step 4 of the course, participants are required to both give and receive a code review. This step could foster collaboration and reinforce learning through peer-to-peer feedback. Participants will submit their code for review and will also be assigned to review the code of another participant, providing constructive feedback based on the step's criteria.

**Acceptance Criteria:**

- [ ] Participants submit their code for review by their peers or volunteers.
- [ ] Participants are assigned to review the code of another participant.
- [ ] Code reviews should include constructive feedback, focusing on code functionality, readability, and adherence to best practices.
- [ ] Both giving and receiving a code review are completed by each participant.
- [ ] Feedback is provided within the agreed timeframe and aligned with course standards.
- [ ] Participants should add the link to the "slack post" asking for review, so volunteers can easily review it

**Dependencies:**

Assignment of code review pairs/groups.
Availability of volunteers or peers to review code submissions.
Platform or process to facilitate code sharing and feedback.

**Comment by kfklein15** [comment]
Waiting for #976

**Comment by Ara225** [comment]
Closing as step 4 is no longer going to exist
