### ISSUE TITLE
Feature : index on UFD module

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#1071]
**Which module(s) and week(s) does this change affect?**
Module(s): User focused Data (should this be called "Taster Module" or "Requirements" 😛 )
Week(s): all

**What is the work that needs to be done?**

I won't add this now as it might be disruptive but on November 1 shall we add an index.html to https://github.com/CodeYourFuture/Module-User-Focused-Data/ with

wireframe and  form controls linked on it - then the preview would obviously link to the learner's work instead of a netlify 404 tht we then type the dir into

The whole repo is deployed to netlify to give fast previews to volunteers on the PRs, but the netlify link is broken because it's in a subdir

**Why is this work important to do?**

**Additional context**

**Who might need to know about this change?**

**Comment by moneyinthesky** [comment]
That's a great idea!

> deployed to netlify to give fast previews to volunteers on the PRs
Also, I've noticed participants get a thrill out of seeing their work deployed at this early stage 😄

**Comment by illicitonion** [comment]
> Module(s): User focused Data (should this be called "Taster Module" or "Requirements" 😛 )

Yes!

> I won't add this now as it might be disruptive but on November 1 shall we add an index.html to https://github.com/CodeYourFuture/Module-User-Focused-Data/ with wireframe and form controls linked on it - then the preview would obviously link to the learner's work instead of a netlify 404 tht we then type the dir into

Yes!

**Comment by SallyMcGrath** [comment]
Fixed in #1241
