### ISSUE TITLE
Images in issues don't render

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#1073]
Go to https://programming.codeyourfuture.io/data-groups/sprints/3/backlog/

Open up "The Brag Diary"

See a broken image

We expect images to correctly render.

**Comment by SallyMcGrath** [comment]
That's so weird - that image is coming from a completely different and new to me github cdn https://private-user-images.githubusercontent.com/

I will look into it

**Comment by SallyMcGrath** [comment]
Update on this. 

This is because this image was created on a ticket on a private repo. GH won't let us access this without a fight that I am not inclined to undertake. 

This is a user error, and should be fixed by the user re-uploading the picture on a public ticket.
