### ISSUE TITLE
Step 3 - ITD: Can multiple links be tracked on a spreadsheet or doc?

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#1078]
**Which module(s) and week(s) does this change affect?**
Module(s): ITD
Week(s): N/A

**What is the work that needs to be done?**
A/C should be adding link to a doc or spreadsheet, in which all links have to be added

**Why is this work important to do?**
ITD on Dashboard doesn't support the ability of waiting for all links to be approved to "pass" participants to the next step.
We have added this to the backlog, but it won't be an easy change

**Additional context**

**Who might need to know about this change?**

**Comment by kfklein15** [comment]
@SallyMcGrath said she would help me with this <3 Thank you!

**Comment by SallyMcGrath** [comment]
Yes - but who is @saf94 ?

**Comment by kfklein15** [comment]
https://codeyourfuture.slack.com/archives/D07U0NVH7HR
