### ISSUE TITLE
1 Slack channel per step

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#1080]
**Which module(s) and week(s) does this change affect?**
Module(s): N/A
Week(s): N/A

**What is the work that needs to be done?**
Create 1 channel for every step on ITD Slack channel

**Why is this work important to do?**
so it's easy to manage questions about the same step

**Additional context**
**Who might need to know about this change?**

**Comment by SallyMcGrath** [comment]
Dupe of #1054 but less detail on this so closing
