### ISSUE TITLE
Rework pair programming assignments

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#1081]
Every sprint in ITP we have a pair programming assignment.

We want to add a bit more structure to how they work.

Here's a proposed update for the issue text - suggestions welcome.

> # [TECH ED] 🫱🏽‍🫲🏿 Mentored pair programming
>
> Pick one piece of programming you're doing (we recommend a codewars kata) and pair up with a volunteer to work on it together.
>
> See [the mentored pair programming guide](https://programming.codeyourfuture.io/guides/pair-programming/mentored/) for guidance.
>
> Book time with a volunteer using one of the Scheduling links in the [#cyf-pair-programming](https://codeyourfutur-yov6609.slack.com/archives/C07PA66MQMC) slack channel's [canvas](https://codeyourfutur-yov6609.slack.com/canvas/C07PA66MQMC). If there are no available times, please post in [#cyf-pair-programming](https://codeyourfutur-yov6609.slack.com/archives/C07PA66MQMC).
>
> Remember, as a learner, you will need to **explain** your thought process, **plan** out what to do, **write** the code and **check** it works
>
> ## Why are we doing this?
>
> Pair programming is an excellent way to develop programming and communication skills. It is often much easier to work through something when working on something 1-to-1. It is also helps our learners to prepare for technical interviews when they'll need to code in front of other people. 
>
> ## Acceptance criteria
>
> - [ ] You have pair programmed on a piece of programming with a volunteer for at least one hour this sprint.

In User Focused Data we will skip the "(we recommend a codewars kata)" text, as codewars starts from Structuring and Testing Data.

**Comment by SallyMcGrath** [comment]
Er, yes, I think makes sense. For ref, it currently says

https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/issues/28

I think retain this line in the actual ticket:

> As a trainee, you will need to **explain** your thought process, **plan** out what to do, **write** the code and **check** it works

And it prompts me to suggest you also include learning objectives in this ticket as you will be mass updating

**Comment by illicitonion** [comment]
The guide is written and published at https://programming.codeyourfuture.io/guides/pair-programming/mentored/, and all ITP tickets have been updated.
