### ISSUE TITLE
Prep Sprint 3

### ISSUE THREAD

**Issue by Della-Bella** [CodeYourFuture/curriculum#1094]
**Which module(s) and week(s) does this change affect?**
Module(s): Prep
Week(s): 3

https://programming.codeyourfuture.io/user-data/sprints/3/prep/#backlog

**What is the work that needs to be done?**
Move the  Backlog which is on prep 3 to the first week Prep

 just wondering why the explanation of the ‘Backlog’ is in the Prep for Sprint 3. Wouldn’t it be clearer if it were located at the beginning of prep 1?

**Why is this work important to do?**
We need to know this at the beginning of the course, as we've already done it by this point.

**Additional context**

**Who might need to know about this change?**

**Comment by illicitonion** [comment]
Thanks for filing this issue, it's a good question!

It looks like the backlog item is _also_ already in the first sprint prep: https://programming.codeyourfuture.io/user-data/sprints/1/prep/#backlog

So I think we should just remove it from this sprint. I agree it's weird that it's in both.

Can I interest you in putting together a pull request to fix this? It should be a quick small task! The curriculum is defined in [this repo](https://github.com/CodeYourFuture/curriculum) - if you fork and clone it, the activities that make up this sprint are in [this file](https://github.com/CodeYourFuture/curriculum/blob/main/org-cyf-itp/content/user-data/sprints/3/prep/index.md?plain=1) - each activity starts with the line `[[blocks]]` and then some information about the activity. If you make a branch, remove the block for backlog from that file, and make a pull request, I can review it and we can get it merged!

If you need a hand, or run into any problems, feel free to DM me on Slack (I'm Daniel Wagner-Hall) and we can work through it together.

Thanks!

**Comment by illicitonion** [comment]
This was done in https://github.com/CodeYourFuture/curriculum/pull/1096
