### ISSUE TITLE
Create a Scrimba FAQ

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#1095]
Create an FAQ with the main questions about Scrimba so we can clarify/pre-empty most questions of our participants.

**Comment by SallyMcGrath** [comment]
https://docs.google.com/presentation/d/1Z10grrFWQcKeEb2iD84ljhq9vzLMPWL5ny6oaotpb8E/edit#slide=id.g30cdef6dcc2_0_31

Going to add this to Slack now
