### ISSUE TITLE
Work out permissions for retro figjam

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#1104]
Every single day-plan ends with a retro block which says folks should use FigJam: https://programming.codeyourfuture.io/user-data/sprints/1/day-plan/#retro

I tried doing this in class this week, and we found:
1. Every participant needed to sign up for an account. This is a one-time cost, but was a bit annoying in class.
2. Participants were unclear as to whether they were meant to sign up for an education account, as this form was shown to them. I'm guessing we probably shouldn't be doing this until they have student emails?
3. Every participant needed to request access to the FigJam I'd created (which doesn't even get flagged in the page - I got emails about each request).

We ended up giving up and doing our retro on Slack.

If we're going to use FigJam, we should work out:
1. What up-front steps do we want participants to do (e.g. by having them set up a Figma account in https://programming.codeyourfuture.io/user-data/prep/#professional-accounts)
2. What per-retro steps are needed (e.g. assigning permissions), and if there's a way to make that smoother (e.g. maybe there's a group we can add folks to or something so that they automatically get permission).

cc @SallyMcGrath who set up the FigJam stuff originally

**Comment by SallyMcGrath** [comment]
Yeah there isn't a perfect solution to this. Miro has this issue where it locks old boards if you make new ones and destroy staff work. Metro Retro is fine, tbh they are all fine, but they all need accounts. Many of the front end project sites and courses like Codeacademy and Front End Practice and Scrimba provide projects as Figma files, so it seemed like the lowest friction thing as they will use it anyway. 

Definitely add it to the accounts. 

Re permissions. I thought I had set the figjam to be open. Did this not work? I put a password on and posted that in Slack, but if you made a copy you should be able to just set as open/anyone can edit.
<img width="454" alt="Screenshot 2024-10-21 at 11 44 57" src="https://github.com/user-attachments/assets/a205e029-81ab-4b38-9565-5f75eca9a6a9">

**Comment by illicitonion** [comment]
I went to share, and "Anyone can Edit" was disabled:

<img width="449" alt="Screenshot 2024-10-21 at 11 48 02" src="https://github.com/user-attachments/assets/75f25a44-51ca-4f75-80eb-221916f0cae9">

When I clicked add a password, I was told this was a pro feature:

<img width="693" alt="Screenshot 2024-10-21 at 11 48 25" src="https://github.com/user-attachments/assets/3741cace-f691-4dbf-8003-133019a5f7a3">

**Comment by SallyMcGrath** [comment]
Oh hm - but you should get Figjam for education in any case.  https://help.figma.com/hc/en-us/articles/360041061214-Verify-education-status

But that doesn't solve it for other volunteers. Could use https://retrotool.io/92Q4EYJYJif-xOuiOy943 ?

**Comment by illicitonion** [comment]
> Oh hm - but you should get Figjam for education in any case. https://help.figma.com/hc/en-us/articles/360041061214-Verify-education-status

Sigh. I had education status, but then I apparently needed to press an _additional_ button to "Upgrade Daniel's team" to actually have it apply to me! Thanks for the nudge! I can now access those settings.

> But that doesn't solve it for other volunteers. Could use https://retrotool.io/92Q4EYJYJif-xOuiOy943 ?

Indeed... Ooh, this looks fancy! Exactly as basic as I want in terms of interface, and I was able to create post-its without signing up. Let's do it!
