### ISSUE TITLE
Add some prep material about setTimeout

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#1115]
Some of the backlog issues in https://programming.codeyourfuture.io/data-groups/sprints/3/backlog/ require using `setTimeout` or `setInterval`.

We currently introduce `setTimeout` later on in a _very_ full sprint teaching general asynchrony and promises https://programming.codeyourfuture.io/data-flows/sprints/3/prep/

I think we should add a block to https://programming.codeyourfuture.io/data-groups/sprints/3/prep/ introducing `setTimeout` (as a "fire and forget" form of asynchrony, where we don't worry about returning results).

This will:
1. Help with the coursework that sprint.
2. Give our learners more experience of passing callbacks around. (They will get confused and stuck on this)
3. Reduce the cognitive load of new concepts in Data Flows Sprint 3 where we're explaining _way_ too many new concepts at once.

**Comment by SallyMcGrath** [comment]
Closed by #1201
