### ISSUE TITLE
Improve Fundamentals prep instructions

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#112]
**Which module(s) and week(s) does this change affect?**
Module(s): Fundamentals
Week(s): prep

**What is the work that needs to be done?**

- Need to clarify the instructions for beginners who are setting up their module repos for the first time
- Explain the purpose of setting up a coursework planner - a way of tracking your work over the course

**Why is this work important to do?**

**Additional context**

**Who might need to know about this change?**

@nirmeet-baweja

**Comment by fcaroline2020** [comment]
Tracking in a separate [issue](https://github.com/orgs/CodeYourFuture/projects/105/views/13?pane=issue&itemId=68383386)
