### ISSUE TITLE
Point trainees at Array and Object Methods Codewars during Data Groups

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#1124]
Every sprint we require trainees to do Codewars.

ITP no longer introduces a bunch of array methods. This is good - just learning about a list of functions isn't useful, practicing using them is!

Fortunately, we have a Codewars collection designed to get people practicing object and array methods: https://www.codewars.com/collections/cyf-array-and-object-methods

We should assign this explicitly. Ideally during Data Groups, trainees should specifically be doing exercises from this collection.

As many as they can do would be great. I'm not sure how best we want to indicate this - probably _not_ by just editing the Codewars ticket in the backlog (if the trainees are anything like me, if they've already done this ticket 5 times, they won't read the 6th one to find out what's new, they'll just assume it's the same).

**Comment by moneyinthesky** [comment]
Maybe instead of the backlog issue having the usual "[TECH ED] Codewars" title, it could be something like "[TECH ED] Practice Array and Object Methods using Codewars" ?

**Comment by illicitonion** [comment]
Sounds good! I'll leave this for y'all to pick up :)

**Comment by SallyMcGrath** [comment]
I dunnit as part of #1137
