### ISSUE TITLE
User Focused Data / Success Criteria - Update

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#1140]
At the moment, we've asked participants to share the link for this coursework: https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/104 when they submit their dashboard step.
I think it may be better to ask them to submit their solution to this issue instead: https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/103 as it may be a better demonstration of the participant's understanding.

Additionally, we can update Success Criteria for each module to ask participants to include a link to their GitHub project board when submitting a step on the dashboard - this will nudge participants to make sure their project board is updated, and will also make it easier for volunteers during reviews.

**Comment by SallyMcGrath** [comment]
fixed in #1241
