### ISSUE TITLE
Distinguish between learning objectives and task objectives

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#1158]
Every sprint success page right now includes morning orientation objectives like "Nominate a timekeeper".

This is not a useful thing to test at the end of every sprint whether you understand, have learnt, and can do.

We should maybe distinguish objectives between "Things you should have learnt" (which we show on success pages) and "Things you were meant to do one time in context" (which we should not).

**Comment by SallyMcGrath** [comment]
#1218
