### ISSUE TITLE
Assign an energiser to the day plans in ITP

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#1168]
Zoom School is suffering from nobody planning or taking ownership, and the energiser especially. It might help to assign something specific, at least for the first half.

Suggest

1. Popcorn show and tell to teach popcorning
2. Screenshare show and tell to check screensharing
3. Breakout and introduce each other to check breakout room
4. Slack mad libs to bring their attention to Slack

**Comment by fcaroline2020** [comment]
@SallyMcGrath apart from suggesting energizers in the dayplan, the ones from your suggest list above I'm guessing they need to be created?
