### ISSUE TITLE
Dead link on the ITD Curriculum Manual 

### ISSUE THREAD

**Issue by ChrisFDev00** [CodeYourFuture/curriculum#1174]
**Describe the bug**

This [page](https://itd.codeyourfuture.io/how-itd-works/#using-the-curriculum) has a link in the first major paragraph

"Volunteers can find these submissions on the dashboard and give feedback. There is a page which just contains the steps in order and that is here: https://itd.codeyourfuture.io/steps/."

The link seems to follow through into a 404 page. I'm not sure whether this is an incorrect or obselete URL, I haven't managed to find a page that seems to be correct for the description so thought best to raise a bug about it.

The repo path for the relevant file is org-cyf-itd/content/blocks/how-itd-works/using-the-curriculum/index.md

*this is the first time I've raised a bug for CYF so I apologise if I've missed any information out.

**Comment by illicitonion** [comment]
Thanks for the issue report, it was very useful and contained a really useful level of detail.

@AmyCYF has fixed this in https://github.com/CodeYourFuture/curriculum/pull/1175 - thanks @ChrisFDev00 and @AmyCYF!
