### ISSUE TITLE
Provision the repo with the common theme (@SallyMcGrath)

### ISSUE THREAD

**Issue by reshamas** [CodeYourFuture/curriculum#1178]
Reminder: 
If the separation of repo is not complete by Nov 14, upgrade Priority to "Urgent"

@daslerr

**Comment by SallyMcGrath** [comment]
## Done

I have forked the repo and removed the course content, leaving the code and the docs: https://github.com/CodeYourFuture/common-theme

## Still to do

- [ ] move the refs to the new place
- [ ] move the docs deployment to the new location
- [ ] test every current site still works
