### ISSUE TITLE
Add reference guide for google docs to ITD step-1

### ISSUE THREAD

**Issue by ChrisFDev00** [CodeYourFuture/curriculum#1191]
**Which module(s) and week(s) does this change affect?**
Module(s): ITD
Week(s): (step) 1

**What is the work that needs to be done?**
I think it would be worthwhile adding a link to the step-1 instructions to a webpage offering a brief introduction to Google Docs/gSuite as a concept.

**Why is this work important to do?**
 I had a participant in a session unaware of Google Docs as a service, so instantly lost focus on the motivation(s) around step-1. It seems reasonable to add a link to help avoid this in the future.

**Additional context**

**Who might need to know about this change?**
@kfklein15 // @SallyMcGrath

**Comment by Ara225** [comment]
Hi,
Thanks for the ticket - got overlooked because the label and team weren't set to ITD (admittedly I didn't tell you to just FYI for future)

**Comment by Ara225** [comment]
Ignore me just saw you made a pull request will mark as done
