### ISSUE TITLE
Sign up as volunteers to be able to review steps in production

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#1198]
All ITD Syllabus volunteers
- Follow the steps on [this canvas](https://codeyourfuture.slack.com/docs/T2H71EFLK/F07RESM32D6) to request access to the Dashboard
- Review 1 person from each region on the Dashboard and different steps
- Gather feedback for discussion next week

**Comment by SallyMcGrath** [comment]
I don't think this team are reviewing tickets in this way yet. Closing for canvas post
