### ISSUE TITLE
Set up "failed deploy" notifications

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#120]
We have nightly build that re-builds our static site every evening, mostly to pick up new content imports from GitHub issues.

We have set up the site to hard-error the build if certain problems are found fetching GitHub issues.

We need to make sure we're notified of these failures so people know to actually act on them.

Ideally a slack message to `#cyf-github-owners` or an email to some relevant group.

**Comment by SallyMcGrath** [comment]
Boop - @illicitonion is this really in progress 🧐

**Comment by illicitonion** [comment]
I sent you a DM about this a while ago :P re-assigning to @SallyMcGrath :)

> It looks like I don't have Slack permissions to do the failed deploy notification thing
> Can you https://app.netlify.com/sites/cyf-curriculum/settings/deploys > Add notification:
>> Event to listen for
>
> Deploy failed
>> Slack Incoming Webhook URL
>
> Set up a webhook URL (probably get one from https://codeyourfuture.slack.com/apps/manage/custom-integrations)
>> Channel
>
>[#cyf-syllabus-tech-feed](https://codeyourfuture.slack.com/archives/C012UUNQ544)

**Comment by SallyMcGrath** [comment]
🙄  🤦‍♀️  Thank you! I have done this now.
