### ISSUE TITLE
Make step review acceptance criteria explicit on Google Sheets coursework

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#1248]
For most of our steps, the acceptance criteria are clear: For PRs they should have been reviewed and that review acted on and have the label complete, for other tasks they're explicitly listed in the ticket.

The Google Sheets exercise on https://programming.codeyourfuture.io/user-data/success/ / https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/104 isn't so obvious. If a new volunteer wanted to review this step, they would probably have to watch the whole video to know whether a linked to spreadsheet is done and correct.

@cjyuan / @SallyMcGrath - you've reviewed _loads_ of these, could you suggest a few bullet points we could add to the issue or the step acceptance criteria on the dashboard so that a new step reviewer can easily verify the Google Sheets project was completed? I'm thinking things like "There is a table named WHERE clause containing 20 rows" - easy to quickly verify.

**Comment by SallyMcGrath** [comment]
Note:I had planned to remove it from the new onboarding module step, so don't spend TOO long on this.

**Comment by illicitonion** [comment]
Ooh that's a good point... We should probably re-add this exercise later on in the course (the whole "thinking about data early on" thing was one of my favourite changes we made)...

**Comment by cjyuan** [comment]
Google sheet should contain


- Original two sheets of data with 100 rows per sheet
- Sheets with data selected using the following queries:
  - simple

  - with multiple WHERE
  - with ORDER BY
  - with GROUP BY
  - query that combines data from multiple sheets

**Comment by SallyMcGrath** [comment]
> Ooh that's a good point... We should probably re-add this exercise later on in the course (the whole "thinking about data early on" thing was one of my favourite changes we made)...

I kept google sheets, just not as a submission criteria on the step
