### ISSUE TITLE
Feature: kitchen sink

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#129]
**Which module(s) and week(s) does this change affect?**
Module(s):
Week(s):

**What is the work that needs to be done?**

create a kitchen sink page with all possible components on it:
page header, blocks, youtube, tabs, codemirror, codefence, mermaid, timeline, breadcrumbs, card

**Why is this work important to do?**

useful for testing
very useful for trainees

**Additional context**

**Who might need to know about this change?**

**Comment by illicitonion** [comment]
This effectively got done by https://common.codeyourfuture.io/
