### ISSUE TITLE
Remove Sally's floating face from pages?

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#141]
On https://curriculum.codeyourfuture.io/fundamentals/prep/ I'm not sure why Sally's face (lovely though it is) is showing up in the middle of the page:
<img width="1088" alt="Screenshot 2023-06-22 at 21 49 54" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/393d4857-d505-4667-b8f0-b57f5c26d0ec">

Or also why Sally's face is clickable but the mysterious OctoCat isn't

**Comment by SallyMcGrath** [comment]
Oh yeah I need to sort that out #68
