### ISSUE TITLE
mermaid rendering is broken

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#143]
On https://curriculum.codeyourfuture.io/fundamentals/prep/ the mermaid isn't rendering:

<img width="1014" alt="Screenshot 2023-06-22 at 22 00 37" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/c2679845-2408-45a4-9fd9-1524fc4b88a2">

**Comment by SallyMcGrath** [comment]
The script isn't showing up in the footer

What should happen:

In render-codeblock-mermaid the page store is set to hasMermaid = true
In scripts.html the script is called if the page store hasMermaid

this is happening with all the other scripts (including others called in the render hook)

Previously Mermaid was loading on every page. Now it's loading on no pages. But we haven't changed the code. So... is it some weird cache in Hugo?
