### ISSUE TITLE
"Unplugged Version" tab is broken

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#145]
On https://curriculum.codeyourfuture.io/fundamentals/sprints/1/day-plan/

<img width="1230" alt="Screenshot 2023-06-22 at 23 58 16" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/f02b2662-d53c-4660-b5cb-56bb1d1127bc">

Clicking the "Unplugged Version" tab doesn't appear to do anything

**Comment by SallyMcGrath** [comment]
It's the same thing as #143  - for some reason the page store isn't storing

**Comment by SallyMcGrath** [comment]
I will fix later, after Tuscan markets

**Comment by illicitonion** [comment]
Closing as duplicate of #143
