### ISSUE TITLE
Closing the hamburger menu scrolls to the top of the page

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#146]
**Describe the bug**

On https://curriculum.codeyourfuture.io/fundamentals/sprints/1/day-plan/ scroll down in the page

Press the hamburger menu

If you then press either the hamburger menu again, or the X in the menu overlay, the menu will go away, and the page will scroll to the top.

I wouldn't expect a scroll to the top when closing a menu.

**Comment by illicitonion** [comment]
By "suppress the visual scroll" do you mean "not scroll" or "jump to a different point"?

If the former, that sounds great.

Here's a video of what I'm talking about, to be super clear; I wouldn't expect pressing a "close" button on an overlay menu to change my position in the main page:

https://github.com/CodeYourFuture/curriculum/assets/1131704/22787931-d0b7-4930-9b4a-d4e4863e21d8

**Comment by SallyMcGrath** [comment]
So, I do want to take the focus to that specific position in the html. For a screenreader or mousefree user, we want to return to the skip link at the end of the menu, to maintain a stable navigation experience. 

If it's bugging you, I could suppress the visual scroll, so it's not as apparent to a mousing user what is happening. I prefer to expose what is happening, but if it's a problem, this is a possible fix.
