### ISSUE TITLE
Dark mode option selection does not persist

### ISSUE THREAD

**Issue by salehpirouzi-cyf** [CodeYourFuture/curriculum#158]
**Describe the bug**

When user selects selects dark mode for the page appearance, the decision is not persisted and going to any other page (or even a simple refresh) would load a light mode appearance.

**How could this be fixed?**
Using the local storage or cookies, I suppose.

**Link to content**
Any page in the curriculum website.

**Comment by SallyMcGrath** [comment]
Fixed by #491 @metinbaris 🙇‍♀
