### ISSUE TITLE
Browser spell check is enabled in non-JS codeblocks

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/curriculum#201]
**Describe the bug**

Non-JS codeblocks (i.e. non-CM6 codeblocks) allows browser spell checking:

<img width="826" alt="Screenshot 2023-07-29 at 21 54 20" src="https://github.com/CodeYourFuture/curriculum/assets/424411/e853505a-a0c1-4818-ae80-b085b8baa94f">

(It seems Chrome's spell checker has some kind of heuristic that ignores works that don't look enough like English)

**How could this be fixed?**

Adding the following attributes `autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"` should disable the spell checker for the attribute ([source](https://stackoverflow.com/questions/254712/disable-spell-checking-on-html-textfields)).

**Who else might need to know about this?**

@CodeYourFuture/global-syllabus

**Comment by SallyMcGrath** [comment]
This is fixed in #248 just needs someone to merge

**Comment by illicitonion** [comment]
Merged!
