### ISSUE TITLE
Migrate Git cheat-sheet into the curriculum, and update https://github.com/CodeYourFuture/bikes-for-refugees/blob/main/README.md to point to it

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#202]
Right now https://github.com/CodeYourFuture/bikes-for-refugees/blob/main/README.md points that the syllabus version of the git cheat-sheet.

1. In a curriculum-not-syllabus world, we should be linking to curriculum content
2. I don't think the git intro week references the cheat-sheet at all, so back-referencing to it doesn't make sense.

We probably want to migrate the cheat-sheet into the new curriculum (should just be a copy+paste of the markdown into a guide), and reference it in the new git intro week.

/cc @Dedekind561

**Comment by SallyMcGrath** [comment]
https://github.com/CodeYourFuture/bikes-for-refugees/commit/d3415762e1b4beafa30746e1bb988224f18b1245
