### ISSUE TITLE
JS1 S1 PD Prep not showing

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#209]
**Describe the bug**
Steps to reproduce
1. Verify that prep for JS1 Sprint 1 is showing on the [PD Syllabus page](https://cyf-pd.netlify.app/blocks/prep-critical-thinking/readme/)
2. Verify that the [PR](https://github.com/CodeYourFuture/curriculum/pull/178) to merge this [didn't fail ](https://deploy-preview-178--cyf-curriculum.netlify.app/js1/sprints/1/prep/) AND was merged
3. Go to the Curriculum website - [JS1 S1 Prep](https://cyf-curriculum.netlify.app/js1/prep/)

**What is wrong with this content?**
Current outcome: prep isn't showing
Expected outcome: prep should show

**How could this be fixed?**
Should I raise another PR?

**Link to content**
All on the steps to reproduce

**Additional context**

**Who else might need to know about this?**
@SallyMcGrath @Dedekind561

**Comment by SallyMcGrath** [comment]
Your changes are showing on https://cyf-curriculum.netlify.app/js1/sprints/1/prep/

You are looking at the overall prep for the module https://cyf-curriculum.netlify.app/js1/prep/ , which has not been updated yet
