### ISSUE TITLE
Embed python tutor visualiser

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#21]
What are people's thoughts on using Python Visualiser temporarily whilst @gregdyke implements the "think like a computer" interpreter?
We can generate iframes:
```html
<iframe width="800" height="500" frameborder="0" src="https://pythontutor.com/iframe-embed.html#code=%0A%0A%0Afunction%20convertToPercentage%28%29%20%7B%0A%20%20%20%20const%20num%20%3D%200.5%3B%0A%20%20%20%20const%20percentage%20%3D%20%60%24%7Bnum%20*%20100%7D%25%60%3B%0A%20%20%20%20return%20percentage%3B%0A%7D%0A%0Aconsole.log%28convertToPercentage%280.5%29%29%3B%0Aconsole.log%28convertToPercentage%280.23%29%29%3B%0A%0A&codeDivHeight=400&codeDivWidth=350&cumulative=false&curInstr=0&heapPrimitives=nevernest&origin=opt-frontend.js&py=js&rawInputLstJSON=%5B%5D&textReferences=false"> </iframe>
```

@CodeYourFuture/syllabus-team

**Comment by Dedekind561** [comment]
If the `iframe` is too clunky then I can just use screenshots for the time being 😄

**Comment by gregdyke** [comment]
Sounds like a great idea to me! It's really cool and quite close to what I have in mind (though it's closer to a paired down debugger than to what I have in mind :) )

**Comment by SallyMcGrath** [comment]
There's nothing wrong with iframes -- just make sure they have a title, please!
