### ISSUE TITLE
Reframe the full stack assessment around completing features

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/curriculum#224]
**Which module(s) and week(s) does this change affect?**
Module(s): Full stack assessment
Week(s): N/A

**Why is this work important to do?**

Completing the [full stack assessment project](https://github.com/CodeYourFuture/Full-Stack-Project-Assessment) is [a requirement](https://docs.google.com/document/d/1jMxqI0L7IKFENCQ8Lw-D1lhnj3c3RZI_WK808wG4YJM/edit) for trainees to join final projects.

In a recent Tech Ed Syllabus team meeting, @SallyMcGrath raised that the structure of the project is problematic and potentially working against the goals of final projects as a whole.

The general structure of the assessment is roughly to:

1. Build the whole frontend
2. Build the whole backend

This causes some issues:

- Trainees are encouraged to spend a lot of time building a lot of "useless" stuff like headers/footers, and not focusing on the main functionality. This approach then bleeds over into the final projects
- There's no thinking about the users or the "product", in other words, trainees aren't thinking about the problem that they are solving
- Trainees don't prioritise completing a whole end-to-end feature, and instead build out only one half of several features

**What is the work that needs to be done?**

We should reframe the exercise to "slice" it so that trainees focus on completing end-to-end features, one at a time (presumably in a priority order).

Hopefully this shouldn't be too difficult, as the underlying content should be still be good, it just needs moving around.

**Additional context**

We would like to complete this before the next cohort gets to take the assessment (excepting LDN10, who are so close that we don't believe we can complete the work before they start).

**Who might need to know about this change?**

@CodeYourFuture/global-syllabus

**Comment by SallyMcGrath** [comment]
We have a workshop that could happen during Node or Databases (it should be 2 hours though not 1) to support this 

https://github.com/CodeYourFuture/CYF-Workshops/tree/main/breakdown

**Comment by sztupy** [comment]
See https://github.com/CodeYourFuture/curriculum/pull/515 and https://github.com/CodeYourFuture/Full-Stack-Project-Assessment/pull/454

Links to https://github.com/CodeYourFuture/curriculum/issues/464

**Comment by Dedekind561** [comment]
@Dedekind561  - to review in next sprint - 12/03/2024
