### ISSUE TITLE
Prepare the transition from Fundamentals -> SDC

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#227]
**Which module(s) and week(s) does this change affect?**
Module(s): Fundamentals
Week(s): 4

**What is the work that needs to be done?**
We need to ensure that there is time allocated for both volunteers and trainees to identify and describe the upcoming setup and prep for the Induction module.

**Why is this work important to do?**

This is important because volunteers and trainees need to, as much as possible, understand the structure of the curriculum _without the intervention of staff_. The curriculum should be a standalone resource that explains itself as it unfolds. In other words, the curriculum should specify time for trainees and volunteers to pause and reflect on upcoming parts of the curriculum. 

**Additional context**

**Who might need to know about this change?**

**Comment by SallyMcGrath** [comment]
Yes I agree with this!
