### ISSUE TITLE
Content: Create coursework around considering input classes and edge cases

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#243]
We should probably also also have a section where we talk about how this code is buggy because it assumes there are no minutes, and prompt the trainees to add a new assertion and fix that themselves. They already have all of the building-blocks they need to do this, so it should just be a matter of re-applying those same concepts around slicing.

I'd be tempted to also set a piece of coursework around considering the classes of input, and interesting edge cases, they would maybe want to test. Let's note in that exercise also that there are two major ways of identifying these classes/edge-cases: "Domain-driven" (i.e. "morning vs afternoon", "midnight and midday", etc), and "Implementation-driven" (e.g. remembering that we need to include the correct minutes isn't necessarily a core _domain_ problem, but we _can_ identify it as an interesting case to test based on knowing what our implementation looks like - we're separating the hours from minutes, so may need to pay extra attention to the idea that we may do something wrong with the minutes). This would be a great discussion for TAs to facilitate on the Saturday.

_Originally posted by @illicitonion in https://github.com/CodeYourFuture/curriculum/pull/19#discussion_r1252280431_

**Comment by fcaroline2020** [comment]
@Dedekind561 @SallyMcGrath @illicitonion 

we do not have enough context to decide if this is relevant to the ITP syllabus team, does this need to be discuss with us or can this be moved / closed?
