### ISSUE TITLE
Make it easy to list a class's pull requests so volunteers have an easy source of things they can look at

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#259]
As a volunteer it's not always obvious what pull requests are ready to review.

Also as a volunteer at class on Saturday, sometimes it's not obvious what to do, if people aren't actively reaching out for help.

Ideally as a volunteer it would be easy to get a list of unreviewed pull requests to look at, and use as prompts to go talk to the authors about issues/misconceptions/misunderstanding.

This may take the form of some kind of GitHub action which automatically labels PRs based on classes, and some kind of viewer to show what would be good to look at for the class.

**Comment by SallyMcGrath** [comment]
#267  please take a look
