### ISSUE TITLE
Add coursework to pair with Tech Ed buddies on a kata

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/curriculum#260]
**Which module(s) and week(s) does this change affect?**
Module(s): All
Week(s): We thought that Week 3 is probably around the best time to do this

**What is the work that needs to be done?**

Add a coursework to each module that gets the trainees to pair with their Tech Ed buddy on a code kata.

We discussed setting specific katas, but realistically this would be more maintenance burden and simply pairing on _any_ kata (even those that the trainee has previously completed) will be productive.

**Why is this work important to do?**

We have tried several assessment strategies but they generally:

- Don't get set by volunteers or done by trainees
- Suffer from being easy to "cheat", either by copying another trainee's solution or using ChatGPT

We therefore think that leaning into a pairing session will help with realistic assessment.

**Additional context**

Discussed on the Tech Ed Syllabus team meeting on 31st Aug.

There were some possible concerns raised around whether the buddy's judgement could be relied upon for assessment (e.g. bias in either direction). But our long-term strategy around improving volunteer/trainee interaction is to lean into community learning, so we think that these concerns could be alleviated by a community mindset.

**Who might need to know about this change?**

@CodeYourFuture/global-syllabus

**Comment by SallyMcGrath** [comment]
@Dedekind561 

Can you build this in to self evaluate?

**Comment by Dedekind561** [comment]
We've currently got this issue: https://github.com/CodeYourFuture/Module-How-our-curriculum-works/issues/11
The instructions aren't substantial here - but I'd need more info on exactly where the coursework would need to go.
