### ISSUE TITLE
Consider what to do about it branching strategies for React & Node modules

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/curriculum#261]
**Which module(s) and week(s) does this change affect?**
Module(s): React & Node
Week(s): N/A

**What is the work that needs to be done?**

Consider and discuss what we should do to change (or not change!) the Git branching strategies for the React and Node modules. 

**Why is this work important to do?**

As discussed here https://github.com/CodeYourFuture/curriculum/discussions/223#discussioncomment-6636643, the React & Node modules both have unusual Git branching strategies. Specifically, they use the "branch from a branch" strategy. This doesn't line up with the rest of the modules, and is somewhat "unrealistic" (although it should be noted that very little of our Git usage is truly "realistic").

Therefore we should decide whether we want to change the coursework to a more standard Git branching strategy, and if so which one.

**Additional context**

This ticket is unlikely to be prioritised for a while: we think that the JS rewrite work is higher priority for now. This is also not affecting any classes until at least next year - likely WM5.

**Who might need to know about this change?**

@CodeYourFuture/global-syllabus

**Comment by SallyMcGrath** [comment]
obsolete
