### ISSUE TITLE
Add instructions for checking out main and making a new branch to HTML/CSS coursework

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/curriculum#264]
**Which module(s) and week(s) does this change affect?**
Module(s): HTML/CSS
Week(s): 2 & 3

**What is the work that needs to be done?**

Add instructions to the Cakes Co coursework (https://github.com/CodeYourFuture/Module-HTML-CSS/issues/13) and Form Control coursework (https://github.com/CodeYourFuture/Module-HTML-CSS/issues/6) on how to:

1. Switch to the `main` branch
2. Create a new branch from `main` for the relevant week's coursework

**Why is this work important to do?**

In https://github.com/CodeYourFuture/curriculum/discussions/223, we discussed how we wanted to introduce Git branching strategies. We concluded that the "feature branch-esque" strategy (i.e. 1 branch per week) is the most "realistic".

Therefore we should add some instructions when trainees will be creating branches for the first time: in week 2 of the HTML/CSS module.

**Additional context**

**Who might need to know about this change?**

@CodeYourFuture/global-syllabus

**Comment by 40thieves** [comment]
I've made a proposal to change the tickets here: https://gist.github.com/40thieves/fb2f9de4999e1b5cfa3b5eb1572d4113. @CodeYourFuture/global-syllabus could you please review?

If we're happy with that, I can copy the changes into the tickets. Also as [noted in a comment](https://gist.github.com/40thieves/fb2f9de4999e1b5cfa3b5eb1572d4113?permalink_comment_id=4680993#gistcomment-4680993) it would be helpful if someone with access to the CYF Youtube account could create "clip" for the relevant piece of the VSCode video.

**Comment by SallyMcGrath** [comment]
I'm happy with it! And I made the clip, I think

https://youtube.com/clip/Ugkx2OzD279ry4XKFNpeyqJTeBqtrbGJfgRq

**Comment by illicitonion** [comment]
LGTM!

**Comment by 40thieves** [comment]
Tickets have now been updated. Closing.
