### ISSUE TITLE
Feature; (and content) Module Success Page

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#266]
**Which module(s) and week(s) does this change affect?**
Module(s): all
Week(s): 4

**What is the work that needs to be done?**

I've been gathering feedback 

I was going to remove the module success page, but now will use it for a limited (5 items) (not the aggregated checklist from sprints) showing all conditions that must be met for the cohort to progress to the next module, as per the module template schema we worked on in 2021

**Why is this work important to do?**

At the moment the module success page isn't really doing much. It was intended, I think, to aggregate all the learning objectives from the module but a) it doesn't do this yet and b) on reflection we don't want it to as it would be an overwhelming pile of tasks.

Instead, in the pursuit of clarity, we should just list the (max 5) things that need to be done for this module to be "complete" and the cohort be able to move on to the next module. I have agreed these core objectives 

- [ ] Every trainee has received and responded to at least one code review
- [ ] Every trainee has opened at least 3 PRs to the module repo, drafts are accepted
- [ ] 70% of cohort is at or beyond milestones

And Syllabus can attach 2 more per module 

**Additional context**

**Who might need to know about this change?**

@Dedekind561  @kfklein15

**Comment by kfklein15** [comment]
@LaraHuzjan , can we please communicate this change to the PD Syllabus team?
We also need to think about which will be the success from a PD perspective (1-2).

**Comment by SallyMcGrath** [comment]
@gregdyke this is the module success criteria (actually broadly drawing from this thing we worked out years ago but couldn't figure out how to execute) https://module-template.codeyourfuture.io/evaluation/exit-criteria
