### ISSUE TITLE
HTML-CSS Sprint 1 - DevTools Workshop - Times don't add up

### ISSUE THREAD

**Issue by varuna-v** [CodeYourFuture/curriculum#308]
**Describe the bug**
The DevTools Workshop is scheduled for 60 minutes, but the workshop contents require us to be working for at least 100 minutes.

**What is wrong with this content?**
The times on the top right of the boxes are incorrect. We ended up skipping part of the workshop in favour of sticking to the schedule. It would be good to correct this for the next cohort.

**How could this be fixed?**
I suggest: 
...
DevTools Workshop 10:20 - 12:20
Lunch 12:20 - 13:20
Study Groups 13:20 - 15:00
Break 15:00 - 15:15
...

Please ratify if that's a good way to structure the day.

**Link to content**
https://curriculum.codeyourfuture.io/html-css/sprints/1/day-plan/

**Additional context**

**Who else might need to know about this?**

**Comment by SallyMcGrath** [comment]
fixed by #404
