### ISSUE TITLE
Add prep content for JS3 Week 2

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#345]

**Comment by SallyMcGrath** [comment]
Hi Mitch, you are still assigned this issue. If you need me to write it, you really need to take your face off it and make this clear. Thanks.

**Comment by Dedekind561** [comment]
I'll put a draft PR up for this issue.

**Comment by SallyMcGrath** [comment]
It doesn't need to be finished. Just put up whatever you have.
