### ISSUE TITLE
Include vscode extension file in Module repos

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#368]
**Which module(s) and week(s) does this change affect?**
Module(s): all
Week(s): n/a

**What is the work that needs to be done?**

We spend a lot of time [asking/begging/demanding](https://curriculum.codeyourfuture.io/html-css/sprints/4/prep/) trainees install Prettier and it really annoys me.

We can include a [vscode recommended extensions file ](https://code.visualstudio.com/docs/editor/extension-marketplace#_recommended-extensions)in their coursework repos to nag them for me.

**Why is this work important to do?**

Our general recs are

## Current recs

Name | ID | Purpose
-- | -- | --
Prettier | esbenp.prettier-vscode | Code formatter - Format your code automatically
ESLint | dbaeumer.vscode-eslint | Linter - Tells you when your code is wrong
Code Spell Checker | streetsidesoftware.code-spell-checker | Tells you when you've spelt something wrong
GitLens — Git supercharged | eamodio.gitlens | Connect with GitHub/Git
Live Server | ritwickdey.LiveServer | Run your code in the browser
Live Share | MS-vsliveshare.vsliveshare | Share your project with a team

## Possible additions

- GitHub CoPilot
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
- [Tailwind Intellisense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss_ (for later modules)
- ??

**Additional context**

**Who might need to know about this change?**

**Comment by 40thieves** [comment]
I was under the impression that we already had a collection of extensions somewhere - but I think it needed some manual intervention to install.

The other thought I had was a Github Action to run Prettier and fail the build if it doesn't pass - unless we already have this? If that's the case then could we make the error more "obvious" - perhaps post a comment on their PR?

**Comment by SallyMcGrath** [comment]
We do have an extension pack (as linked in the ticket) but the problem is they don't install it. The recommended extensions file prompts them when they open the repo in VSCode.

**Comment by pseudopilot** [comment]
Here is the list of repos I'm going to update:

**ITP:**
https://github.com/CodeYourFuture/Module-User-Focused-Data
https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data
https://github.com/CodeYourFuture/Module-Data-Groups
https://github.com/CodeYourFuture/Module-Data-Flows

**The Current Curriculum:**
https://github.com/CodeYourFuture/Module-HTML-CSS
https://github.com/CodeYourFuture/Module-JS1
https://github.com/CodeYourFuture/Module-JS2
https://github.com/CodeYourFuture/Module-JS3
https://github.com/CodeYourFuture/Module-React
https://github.com/CodeYourFuture/Module-Servers
https://github.com/CodeYourFuture/Module-Databases

**Projects:**
https://github.com/CodeYourFuture/group-project-bookshelf
https://github.com/CodeYourFuture/CYF-Code-Review-Group-Project/tree/master
https://github.com/CodeYourFuture/group-project-jsf-time
https://github.com/CodeYourFuture/terminal-tic-tac-toe
https://github.com/CodeYourFuture/1000-Paper-Cranes
https://github.com/CodeYourFuture/Codewars-API-Project
https://github.com/CodeYourFuture/GitHub-Activity-Project
https://github.com/CodeYourFuture/CLI-Treasure-Hunt

**Comment by pseudopilot** [comment]
I have a bash script to make it fast (which I tested with one repo already). But I can't push to the other repos yet.
To make me eligible to push my branch to the first repo @illicitonion set ITP team as maintainers of the repo.
Either we need to do it for all the repos or I can just hand the script to anybody who has full access already.

**Comment by JayMayer** [comment]
@pseudopilot Thanks for the adding these! I'm wondering when in the curriculum we should ask trainees to explore this fancy new approach and install recommended extensions.

We [introduce VS Code](https://cyf-programming.netlify.app/user-data/prep/#install-vs-code) at a different time to [cloning a Git repo](https://cyf-programming.netlify.app/user-data/sprints/1/prep/#working-locally). That leaves a [backlog task in Sprint 3](https://github.com/CodeYourFuture/Module-HTML-CSS/issues/53) which mentions the existing extension pack. Unless there's alternative suggestions, I'll make the edit to the backlog issue and ask trainees to:

1. In VS Code, open the Extensions pane (View > Extensions)
2. Search for `@recommended` in the search bar
3. Click on the button for "Install Workspace Recommended Extensions" (displayed as download arrow icon inside the cloud)
<br/>

P.S.: It's possible to get VS Code to suggest the [CYF extensions pack](https://marketplace.visualstudio.com/items?itemName=CodeYourFuture.cyf-extension-pack) with:
```json
{
  "recommendations": [
    "CodeYourFuture.cyf-extension-pack"
  ]
}
```

... however I'm not a fan in this case. It hides what is going on, showing only the extension pack in the Extensions pane, and not each individual extension to be installed.

**Comment by pseudopilot** [comment]
@JayMayer , thank you. Honestly I didn't know we could use an extensions pack in recommendation. 😃 Now I know 😎
