### ISSUE TITLE
https://github.com/CodeYourFuture/Module-JS2/issues/30 is light on detail and a bit unclear

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#379]
https://github.com/CodeYourFuture/Module-JS2/issues/30 is light on detail - reading it, it's not clear what product people are meant to be designing, or what the Agile Development class is referring to.

I'm assuming it's probably roughly "pick a product you use in real life" (e.g. Spotify / Google Maps / whatever), but we should edit the issue to be clear.

We should flesh out some detail here.

/cc @LaraHuzjan @kfklein15

**Comment by kfklein15** [comment]
@esma-g , this was your content. See on this issue feedback from Daniel - he's been to some of the classes and seen them being delivered.

**Comment by esma-g** [comment]
> @esma-g , this was your content. See on this issue feedback from Daniel - he's been to some of the classes and seen them being delivered.

We talked about it in [this Slack post](https://codeyourfuture.slack.com/archives/C01KMRERKS5/p1700334087657399?thread_ts=1700334087.657399&cid=C01KMRERKS5). Sally closed the coursework issue as it should have been deleted. Teamwork project doesn’t happen in JS2 anymore, it's in JS3.
