### ISSUE TITLE
Make the menu icon more obviously an icon

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/curriculum#39]
**Which module(s) and week(s) does this change affect?**

Module(s): N/A
Week(s): N/A

**What is the work that needs to be done?**

I'm not actually sure what the best outcome is here. My suggestions:

- Change the icon to be a 🍔 icon (i.e. not randomised)
- Change the icon to be something more "standard" (e.g. ☰)

**Why is this work important to do?**

Currently, the icon for the nav menu is a randomised set of emojis, e.g.:

<img width="69" alt="Screenshot 2023-06-08 at 21 45 11" src="https://github.com/CodeYourFuture/curriculum/assets/424411/ce72eacd-f21f-43b4-912d-81e2faeb9304">

Both myself & @illicitonion didn't immediately recognise that it was a menu icon. This suggests that others would also not be able to find the menu and the content within it.

**Who might need to know about this change?**

@CodeYourFuture/global-syllabus

**Comment by SallyMcGrath** [comment]
#41 resolves this

**Comment by SallyMcGrath** [comment]
@illicitonion If PRs are going to be blocked without review, pls review as we are BACKING UP
