### ISSUE TITLE
JS2 is missing a success page, and the progress check-in block is unclear

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#395]
**Describe the bug**

https://curriculum.codeyourfuture.io/js2/sprints/4/day-plan/#progress-check-in

This block links to an success empty page.

It's also unclear who should be doing a progress report (a trainee? a volunteer?), and how (it just says "to the organisation" - is there a person or slack channel or something this should happen to?)

I think the success page should contain milestones roughly encompassing (but framed as more testable LOs):
* I am confident with all of the content of JS1 (defining and calling functions, variables)
* I can create and consume arrays and objects, and write a for loop
* I would be comfortable making a new project using DOM APIs
* I have met my milestones (which we should enumerate)

We should also clarify who is meant to report progress, and how.

**Comment by SallyMcGrath** [comment]
Can we talk about this a bit because I think there's a LOT of context you may need.

While your LOs are good things to aim for, I don't think they can do what this page is trying to do.
