### ISSUE TITLE
Trainee tracker tracks total number of PRs, not number of PRs to a module

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#396]
**Describe the bug**

I just looked at the WM5 trainee tracker, and there were trainees counted as on-track for number of PRs for JS2, who hadn't raised a single PR against JS2.

This appears (though I haven't delved deep) to be because we count the total number of PRs (and treat that as a cumulatively increasing number in terms of milestones) instead of counting number of PRs to the module being considered.

We should consider changing this so that we can give better feedback to trainees about their progress.

**Comment by SallyMcGrath** [comment]
By all means improve the tracker, which is a terrible spreadsheet I wrote 2 years ago and have been attempting to replace ever since. 🙏 🙇 

However, we are looking at the PR tab with our eyes and thinking about it with our minds... It's meant to help us with not command us.
