### ISSUE TITLE
Mermaid diagrams in CYF workshops (possibly any external markdown) render with an error

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/curriculum#411]
**Describe the bug**

If a Mermaid diagram is included in an "external" markdown file, e.g. included via CYF-Workshops then it renders with an error on the curriculum.

See an example with [the debugging workshop](https://curriculum.codeyourfuture.io/js3/sprints/3/day-plan/#break-down) in the day plan for JS3W3 (have to click the "Recap asking questions" accordion):

![Screenshot 2023-12-01 at 22 32 19](https://github.com/CodeYourFuture/curriculum/assets/424411/21fcb0c2-5327-4bde-8d0d-07f872360252)

I'm guessing this console error is related:

```
Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at app.min.js:1:1044
```

**What is wrong with this content?**

It borked.

**How could this be fixed?**

Haven't dug into it, but based on the console error, perhaps we're not processing the Mermaid for external markdown files properly?

**Link to content**

https://curriculum.codeyourfuture.io/js3/sprints/3/day-plan/#break-down (have to click the "Recap asking questions" accordion)

**Additional context**

Spotted while reviewing https://github.com/CodeYourFuture/curriculum/pull/400

**Who else might need to know about this?**

@CodeYourFuture/global-syllabus

**Comment by 40thieves** [comment]
@SallyMcGrath Thinks that it is somewhere in: `{{ $response.content | base64Decode | replaceRE "<!--" "" | replaceRE "-->" ""  | markdownify }}`

**Comment by SallyMcGrath** [comment]
Hey, it actually could conceivably be a loading issue

I triggered this inside prep view. What about moving the module out of scripts partial and back into the render hook?

**Comment by 40thieves** [comment]
@SallyMcGrath I think this is fixed now?

**Comment by SallyMcGrath** [comment]
I fixed the external workshop issue. I did NOT fix the prep view issue, which is more gnarly. (But I did just complete React, Node, and JS3 so I'm giving myself some leeway)

**Comment by Dedekind561** [comment]
Update: I tried to make sense of this issue and now have a better grasp of why it's happening (i.e. the conflict between `solo-view.js` and the Mermaid write) but I didn't know where to go from there. Might help if I pair up with someone on this.
