### ISSUE TITLE
Add a tour of VS Code

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#415]
https://syllabus.migracode.org/courses/introduction-3/course-content/introduction-2/dev_tools#development-tools has some useful screenshots and introductions to some VS Code UI surfaces

I'd also really like to introduce trainees to the idea of Ctrl/Cmd+Click, and Ctrl+- and Ctrl+Shift+- to help them navigate between call sites, definitions, etc.

**Comment by 40thieves** [comment]
> Ctrl+- and Ctrl+Shift+-

TIL what these do!

**Comment by illicitonion** [comment]
> > Ctrl+- and Ctrl+Shift+-
> 
> TIL what these do!

They are my absolutely number one shortcuts! Command-click your way through the world, and trivially jump back and forth between contexts! Most things I can jump to a context menu if I need, but navigating between call-sites and definitions...

**Comment by 40thieves** [comment]
Here's what is currently shown in the [MigraCode](https://syllabus.migracode.org/courses/introduction-3/course-content/introduction-2/dev_tools#development-tools) materials:

- Autocomplete
- File view
- The keyboard shortcuts for triggering fuzzy search (but not actually fuzzy search itself)

I think we could look at expanding this a little and perhaps re-ordering:

- File tree
- Fuzzy search (both the shortcut to trigger and the search UI itself)
- Built-in terminal
- Autocomplete
	- Possibly mention the ways to manually trigger it?
- Code navigation
	- <kbd>Cmd</kbd> <kbd>Click</kbd>
	- <kbd>Ctrl</kbd> <kbd>-</kbd> / <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>-</kbd> (back / forward)
- Should we include the Search pane?

The Git pane is already covered in our [Git tutorial](https://curriculum.codeyourfuture.io/induction/sprints/1/prep/#-working-locally), so I'm leaning against adding that just to constrain the length.

Another question I have is where this content should live. I suppose the most obvious place is as a guide, but I'm not convinced anyone reads those. I was thinking that if I make it a guide I should also link it from somewhere in the Induction module.

If that seems like a sensible proposal I'll go ahead and start writing it up. (Will have to disable all my settings to get VS Code back to the defaults but that's ok 🙂)

**Comment by ChrisOwen101** [comment]
@illicitonion @40thieves How would you both feel is this content was supplemented with a video of it in action? More generally, how do we feel about custom made videos in the curriculum?

**Comment by illicitonion** [comment]
Sounds great! We already have videos in the curriculum, they're easily embedded from YouTube. (Ideally these would supplement rather than replace text :))

**Comment by moneyinthesky** [comment]
We had a similar issue raised in ITP a few weeks ago - as such we added a video intro to the VSCode layout which can be seen here: https://cyf-programming.netlify.app/user-data/prep/#install-vs-code
