### ISSUE TITLE
Feature: make titles useful in search results

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#426]
**Which module(s) and week(s) does this change affect?**
Module(s): na
Week(s): na

**What is the work that needs to be done?**

Given a page in the curriculum
When I type in the search bar
Then all the results are called Home
<img width="1509" alt="Screenshot 2023-12-04 at 08 38 53" src="https://github.com/CodeYourFuture/curriculum/assets/42203406/bcafabbb-3f5c-4c89-a9c2-6529e08c6cde">
<img width="1512" alt="Screenshot 2023-12-04 at 08 41 29" src="https://github.com/CodeYourFuture/curriculum/assets/42203406/5e34a733-7b1d-4ca1-9ea9-06511326e4d8">

We want that title to provide more context, like HTML-CSS Sprint 2 Prep

I think this is likely a very small templating task updating line 4 of head.html

**Why is this work important to do?**

**Additional context**

**Who might need to know about this change?**

**Comment by metinbaris** [comment]
Hello @SallyMcGrath I am having "API rate limit exceeded for {MY_IP_ADDRESS}" error when I run the command 

`rm -rf public &&
hugo && npx pagefind --source "public" --serve`

Is there anything I can do besides adding : --header 'Authorization: Bearer {MY_GITHUB_TOKEN}' ?

**Comment by SallyMcGrath** [comment]
Hmm, I'm not hitting that

Have you installed env?

What happens when you run `rm -rf public && dotenv hugo && npx pagefind --site public --serve` ?

**Comment by metinbaris** [comment]
@SallyMcGrath encountered the same error after running the similar command you provided:
rm -rf public && hugo && dotenv npx pagefind --site public --serve

The error message I received is: "API rate limit exceeded for {{MY_IP_ADDRESS}}."

Should I also update the following parameters on .env file?
GITHUB_CLIENT_ID="clientid"
GITHUB_CLIENT_SECRET="clientsecret"

**Comment by SallyMcGrath** [comment]
No, that won't help as the client is for the clone issues tool.

Your error seems more likely to do with your fine grained access token for CYF_CURRICULUM...etc . If you're sure your access token is valid and has not expired (check the readme for details) then you could try running your local with these API errors suppressed:

`ignoreErrors = ["error-remote-getjson"]`

Don't commit that line to hugo.toml /config.toml

**Comment by SallyMcGrath** [comment]
Also sometimes you do just hit the limit and GitHub tells you off for a bit. Have you been working too hard? 😉 

Really I want to cache all this for local development as it's a huge pain when you've no connection, as well.

**Comment by metinbaris** [comment]
Oh I also noticed this one in error logs:
tls: failed to verify certificate: x509: “Fortiguard SDNS Blocked Page” certificate is not standards compliant
