### ISSUE TITLE
Set up a dev mode and put caching on

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#431]
**What is the work that needs to be done?**

Stuff like getting paginated issues slows us down and is rarely helpful in dev.

I'd like a speedier devmode which doesn't constantly pull from the apis. Ideally one I can run offline on planes!

`hugo.IsProduction` could help maybe?

**Why is this work important to do?**

**Additional context**

**Who might need to know about this change?**

**Comment by illicitonion** [comment]
@40thieves Did you follow the `export CYF_CURRICULUM_GITHUB_BEARER_TOKEN ` step in https://github.com/CodeYourFuture/curriculum?tab=readme-ov-file#to-run-locally?

I reliably get rate-limited if I forget that step, and reliably don't when I do the step.

**Comment by 40thieves** [comment]
After a more concerned debugging effort I've got it figured out now. I've also realised that Github tokens can be set to expire after 1 year (max), so that is very helpful.

**Comment by SallyMcGrath** [comment]
> After a more concerned debugging effort I've got it figured out now. I've also realised that Github tokens can be set to expire after 1 year (max), so that is very helpful.

Could you briefly detail the issue, Ali? If you hit it, others likely will too.

**Comment by 40thieves** [comment]
I think it was a number of very silly errors 🤦🏻 Typo-ing the `export`ed variable name and not correctly pasting the key (idk why but it kept pasting an old value)

**Comment by SallyMcGrath** [comment]
> @40thieves Did you follow the `export CYF_CURRICULUM_GITHUB_BEARER_TOKEN ` step in https://github.com/CodeYourFuture/curriculum?tab=readme-ov-file#to-run-locally?
> 
> I reliably get rate-limited if I forget that step, and reliably don't when I do the step.

What step is this? I can't see this command in the readme.

**Comment by SallyMcGrath** [comment]
@illicitonion can I beg you to take a look at this because your change for issue pagination has made the site build so slowly I am considering building a new platform!! It's unbearable!

I don't care about issue pagination in local development. Can you move it to production only please?
