### ISSUE TITLE
Remove "Is the string uppercase?" kata from JS-1 Week 3 Codewars collection

### ISSUE THREAD

**Issue by JayMayer** [CodeYourFuture/curriculum#437]
**Which module(s) and week(s) does this change affect?**

Module(s): JS-1
Week(s): 3

**What is the work that needs to be done?**

Remove the "Is the string uppercase?" kata from the "JS-1 Week 3" Codewars collection, possibly replacing with a similar kata.

**Why is this work important to do?**

This kata has confused a large number of trainees, as the provided setup expects the solution to use a method on the String prototype.

To pass the kata, an understanding of object-oriented concepts is required, and they are not yet taught at this point in the curriculum.

**Additional context**

CYF Authored Collection: https://www.codewars.com/collections/cyf-js-1-week-3
Kata: https://www.codewars.com/kata/56cd44e1aa4ac7879200010b

**Who might need to know about this change?**

@Dedekind561

**Comment by SallyMcGrath** [comment]
Thanks, @JayMayer ! I've removed it. BTW there's a channel #cyf-codewars to share these insights as well.
