### ISSUE TITLE
Fundamentals: Checkboxes don't seem clickable

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#45]
**Describe the bug**

I've seen @SallyMcGrath demo clicking on checkboxes before and them turning into a "complete" state - that doesn't seem to work on the fundamentals prep page. Not sure if this is intentional.

**What is wrong with this content?**

Clicking on these checkboxes doesn't change their state:

<img width="915" alt="Screenshot 2023-06-10 at 23 10 14" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/2c5449de-7da0-4b5b-8727-3026da1d12d8">

**Link to content**

https://cyf-curriculum.netlify.app/fundamentals/prep/

**Comment by SallyMcGrath** [comment]
This is copy pasted from the old syllabus, where it just uses unclickable checkboxes.

Do we want them always to be clickable? I think I can intercede with a render hook

**Comment by illicitonion** [comment]
I think if we're going to use this style consistently, the links should be consistently clickable, so I'd lean to yes. Otherwise I think we should use a different style, but I'd lean yeah, let's make them all clickable.

**Comment by SallyMcGrath** [comment]
Will do!

**Comment by SallyMcGrath** [comment]
closed by #111  and #47
