### ISSUE TITLE
User Focused Data - Sprint 1 - Timings

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#457]
**Which module(s) and week(s) does this change affect?**
Module(s): all
Week(s): all 

**What is the work that needs to be done?**

Now we have the solo view running on prep pages, it's made the timing errors clearer eg

https://deploy-preview-438--cyf-curriculum.netlify.app/js3/sprints/1/prep/#single-datum

is set at 30 minutes for 4 sentences. We need to run a little sweep over these views and sparkle up the timings and make them make sense.

**Why is this work important to do?**

**Additional context**

**Who might need to know about this change?**

**Comment by JayMayer** [comment]
Changing the scope of this issue to be for Sprint 1 only. As future sprints are worked on, we can create issues to sweep their timings.

**Comment by SallyMcGrath** [comment]
closed by #985
