### ISSUE TITLE
Fundamentals: Exercise times seem to exceed section times

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#46]
**Describe the bug**

"Agreements" claims to be 5 minutes, but contains an exercise which claims to be 58 minutes. Given the exercise is part of the section, this doesn't seem consistent/compatible.

**What is wrong with this content?**

<img width="1276" alt="Screenshot 2023-06-10 at 23 44 33" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/b5ea4caa-4cc2-48c0-a6e0-a25bcb612b3f">

**How could this be fixed?**

**Link to content**

https://cyf-curriculum.netlify.app/fundamentals/prep/

**Comment by SallyMcGrath** [comment]
It's calculating correctly based on the information given. 

This is like this because PD have written it this way. I'm not sure why they have done it, but it's probably better for us to figure out what they meant in the first place instead of fixing it ourselves.

**Comment by esma-g** [comment]
Thanks both. I don't know about this, Karen would answer when she is back from holiday.

**Comment by kfklein15** [comment]
I asked about this on [Slack](https://codeyourfuture.slack.com/archives/C012UUW69S8/p1686049489388909), @SallyMcGrath , and never got a response. If you could let me know how the logic works, that would be very helpful.

**Comment by SallyMcGrath** [comment]
Karen's GWT copied from Slack 

GIVEN a block is 60 min long
WHEN I add exercise 1 that is 15 min long
THEN I will add 60 min on the first time field
AND 15 min on the exercise time
