### ISSUE TITLE
Migrate all trainee hosting instructions towards Netlify + Supabase

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#464]
We have historically used all sorts of platforms for trainees to host things - Heroku, Render, Elephant, ...

We recently decided to standardise on Netlify for frontends, Netlify with their serverless wrapping of Express for backends, and Supabase for databases.

See discussion in https://github.com/CodeYourFuture/curriculum/pull/463

@sztupy has kindly offered to update the curriculum to make sure this is consistent throughout!

**Comment by sztupy** [comment]
See https://github.com/CodeYourFuture/curriculum/pull/515 and https://github.com/CodeYourFuture/Full-Stack-Project-Assessment/pull/454

Links to https://github.com/CodeYourFuture/curriculum/issues/224
