### ISSUE TITLE
Fundamentals Prep: Skip links are confusing

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#48]
**Describe the bug**

There's a paperclip link that hovers over the content on the right-hand side. It appears to go to an anchor at the top, and make a button in the top-left appear which says "Skip to main".

I'm not sure why it's there or what it's for - the paperclip icon doesn't have an obvious meaning to me, jumping to top can be useful but it's not clear that's what it does and there are browser-native shortcuts to do so, and showing a "Skip to main" button which appears to unconditionally scroll the content by about 50px doesn't seem super useful?

I'm not sure if these are better tailored to different styles of pages with different layouts, but right now on this page the paperclip is a bit distracting and I'm not really sure why it's there...

Screenshot with paperclip:
<img width="1489" alt="Screenshot 2023-06-11 at 00 00 48" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/76ba9a2f-ee63-44be-8286-5daf67bfb28d">

Screenshot of "Skip to main" button:
<img width="1576" alt="Screenshot 2023-06-11 at 00 01 09" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/8064f5d1-140d-4c62-b1d6-70b3f5a95810">

Screenshot after clicking "Skip to main" button:
<img width="1495" alt="Screenshot 2023-06-11 at 00 01 17" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/0b005329-c2ea-43f2-a349-4ebaad1b5e2c">

**Link to content**

https://cyf-curriculum.netlify.app/fundamentals/prep/

**Comment by SallyMcGrath** [comment]
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html

**Comment by 40thieves** [comment]
Seems like the intention is that the paperclip a "Jump to Top" link, which is fairly common, but I personally wasn't aware that it's WCAG requirement. (The Skip to main link *is* a requirement - as Sally's link above shows).

Maybe I'd suggest a tweak to the emoji to make it clearer: what about using 🔝 instead?
