### ISSUE TITLE
[TECH ED] Apply Magic Sauce - Wrong orientation on https://applymagicsauce.com/demo

### ISSUE THREAD

**Issue by PERicci** [CodeYourFuture/curriculum#510]
As requested in this issue, we have to access the webpage https://applymagicsauce.com/demo and follow the instructions there to predict our psycho-demographic profile from the digital footprints of our behaviour.

When we click on 'Upload Facebook Data', we have the option to click on 'How to get my Facebook data?' and see a video tutorial (or the slides under the video) explaining how we can download our personal information from Facebook.

That tutorial is outdated, as Facebook changed its interface. Besides that, the way that Facebook categorises our data changed a little too. So, we are unable to find the information by the exactly same names of the tutorial.

Please watch the tutorial below, recorded by me, showing the new way to request personal information download from Facebook.

https://www.youtube.com/watch?v=MqIffy1oTdU

**Comment by SallyMcGrath** [comment]
Looks like this is about https://github.com/CodeYourFuture/Module-JS2/issues/52

**Comment by SallyMcGrath** [comment]
I let them know about this via https://applymagicsauce.com/contact-us:

> Hi there
> 
> I set your research as an insight and discussion exercise for my trainees: https://github.com/CodeYourFuture/Module-JS2/issues/52
> 
> Recently they reported that your demo is out of date, and recorded their own version to fix this: https://github.com/CodeYourFuture/curriculum/issues/510
> 
> Just letting you know about this as you may wish to update your materials.
> 
> Thanks!
> 
> Sally McGrath
> Code Your Future

**Comment by SallyMcGrath** [comment]
Updated the ticket https://github.com/CodeYourFuture/Module-JS2/issues/52
