### ISSUE TITLE
Fundamentals Prep: Broken link: "Backlog"

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#52]
**Describe the bug**

On https://cyf-curriculum.netlify.app/fundamentals/prep in the Backlog section there is a link with text "Backlog" to https://cyf-curriculum.netlify.app/fundamentals/backlog/ - it goes to a 404.

<img width="867" alt="Screenshot 2023-06-11 at 10 57 50" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/e869780e-5ce2-4de4-97f7-dfa832e3afb6">

**Comment by SallyMcGrath** [comment]
fixed in content updates #42

**Comment by SallyMcGrath** [comment]
No it's not!!
