### ISSUE TITLE
work load

### ISSUE THREAD

**Issue by BakhatBegum** [CodeYourFuture/curriculum#526]
I kindly request volunteers to take a look at the JS2 week-3 backlog and help alleviate the workload. Personally, completing all four build issues within a week is quite challenging for me. Each build takes more than a day and a half, and while it’s possible to rush through, I believe learning JavaScript requires consistent practice and understanding of logic. Additionally, there are other tasks that need attention, and we also require time for preparatory practice. Your assistance in this matter would be greatly appreciated.

**Comment by SallyMcGrath** [comment]
Hey there, 🤗 can I ask that you use the template provided? 

Remembering how to ask good developer questions, does this issue contain all the context someone  (who does not already know what you are talking about) might need to help you? Are there links to the material you reference? 

The link I provided on Slack contained [a template issue. ](https://github.com/CodeYourFuture/curriculum/issues/new?assignees=&labels=enhancement&projects=&template=change-request.md&title=)

Please use the resources provided to communicate your issue in a way that makes it possible for others to help. 🙏

**Comment by fcaroline2020** [comment]
Added this as a point to a new [issue](https://github.com/orgs/CodeYourFuture/projects/105/views/13?pane=issue&itemId=68383386)
