### ISSUE TITLE
Merge in Cloud Module into Main Curriculum

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/curriculum#531]
There is a Cloud/DevOps module that lives here

https://main--cyf-cloud-track.netlify.app/cloud/

It needs to be brought into our curriculum

**Comment by SallyMcGrath** [comment]
Previous cloud

https://module-cloud.codeyourfuture.io/overview/welcome-to-devops

Also many resources here

https://systems.codeyourfuture.io/

Also: developing a track 

https://docs.google.com/document/d/1xJSTOCWAm4nOvDR8lppG9EKHVbiUR8-A4nt9iI_tLLs/

**Comment by SallyMcGrath** [comment]
I will be porting into main while cloud continue to work in their fork for now. Here's what I will be doing:

- [ ] Move all coursework to tickets on here: https://github.com/orgs/CodeYourFuture/projects/151/views/1 with estimated timings given
- [ ] Move explainers, long form etc into blocks on prep view with objectives and estimated times attached to the blocks
- [ ] Move the learning objectives into the blocks they describe
- [ ] Create a day plan with blocks guiding the group to do study, q&a etc, basically as it already says but with timings given to create a schedule
- [ ] Fix typos, simplify language, break up long sentences

**Comment by Dedekind561** [comment]
I've just merged the outstanding cloud translation PR so hopefully this can be marked as done.
