### ISSUE TITLE
[TECH ED] Book Library - Link to the coursework leads to a Error 404 page

### ISSUE THREAD

**Issue by PERicci** [CodeYourFuture/curriculum#536]
**Describe the bug**
The hyperlink to the coursework is incorrect in the 'Link to the coursework' section. When clicking on [this link](https://github.com/CodeYourFuture/Module-JS3/blob/main/book-library/task.md), it leads to a GitHub Error 404 page.

**What is wrong with this content?**
The link provided is not directing to the correct location.

**How could this be fixed?**
The correct link to the coursework appears to be https://github.com/CodeYourFuture/Module-JS3/blob/main/book-library/readme.md.

**Link to content**
 https://github.com/CodeYourFuture/Module-JS3/tree/main/book-library

**Comment by illicitonion** [comment]
Thanks for the report! I just fixed up the link in https://github.com/CodeYourFuture/Module-JS3/issues/4 and the site should now be fixed :)
