### ISSUE TITLE
Fundamentals Prep: Tabs are a bit confusing

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#54]
**Describe the bug**

On my first pass, I didn't realise the "What is GitHub" was a clickable tab with content behind it - maybe worth getting rid of the tab and in-lining the content as a new section after "Getting Started"? Or if not, referencing "You should watch the video in the What Is GitHub tab" in the text somewhere.

On https://cyf-curriculum.netlify.app/fundamentals/prep

<img width="1254" alt="Screenshot 2023-06-11 at 11 22 36" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/a40f25cb-ee4a-42cf-8527-1cd360cb2184">

**Comment by SallyMcGrath** [comment]
The pages are way long so we do need tabs, but maybe they are now too subtle (I found the old style obnoxious)

Let's punch up the tab effect a bit and see if that helps, and also ref in text.

**Comment by 40thieves** [comment]
I figured I'd just go ahead and add the explicit reference in the text: https://github.com/CodeYourFuture/curriculum/pull/77

I think Sally is better placed than me to punch up the visuals though 🙂

**Comment by SallyMcGrath** [comment]
Fixed by #67
