### ISSUE TITLE
Youtube video is missing

### ISSUE THREAD

**Issue by metinbaris** [CodeYourFuture/curriculum#548]
" 📼 Watch: What is GitHub" video is missing

1) Go to:

https://curriculum.codeyourfuture.io/fundamentals/prep/

2) Click Watch: What is GitHub on nav

Video is not there

**Comment by SallyMcGrath** [comment]
It looks like loads of videos have disappeared

https://curriculum.codeyourfuture.io/js1/sprints/1/day-plan/ is also missing for example

I'm looking right now

**Comment by metinbaris** [comment]
Thanks for your reply @SallyMcGrath, yeah maybe templating of {{youtube}} element is not working for .md files

**Comment by SallyMcGrath** [comment]
fixed in #550
