### ISSUE TITLE
Fundamentals Prep: Should there be an <hr> after the "Getting Started" section?

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#55]
**Describe the bug**

<img width="437" alt="Screenshot 2023-06-11 at 11 23 34" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/5a25f2fa-a1b6-4a13-a898-b56f446548f9">

Each other section has an `<hr>`-ish element between them - there isn't one between "Getting Started" and "Agreements" - should there be?

**Comment by ritik2358** [comment]
Could you please assign me this issue?
