### ISSUE TITLE
JS3 Week2 Backlog - [TECH ED] TV Show Project - Part 2/4 - Wrong level in first line

### ISSUE THREAD

**Issue by PERicci** [CodeYourFuture/curriculum#566]
**Describe the bug**

In the first line, where it reads 'Your goal this week is to complete level 400,' the level is incorrect as it does not align with the subsequent guidance:
'Achieving level 200 yourself in someone else's repository.'

**What is wrong with this content?**
Incorrect level in the first phrase.

**How could this be fixed?**
The correction should be:
'Your goal this week is to complete level 200.'

**Link to content**
https://github.com/CodeYourFuture/Module-JS3/issues/20

**Comment by Dedekind561** [comment]
Thankyou for catching this @PERicci , I've just updated the issue
