### ISSUE TITLE
Fundamentals Context page has spurious "minutes" marker

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#58]
**Describe the bug**

<img width="1229" alt="Screenshot 2023-06-11 at 13 27 47" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/08f817be-9c50-4ff9-b1f1-f91c89bba953">

There's a "minutes" on the RHS. I think it should probably be removed, as there isn't really a time-allocation for this context page, but if not we should make sure it has a value.

This is on https://cyf-curriculum.netlify.app/fundamentals/ under the "Context" tab.

**Comment by SallyMcGrath** [comment]
related to #68
