### ISSUE TITLE
Launch content isn't showing on Curriculum

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#586]
**Describe the bug**
We have merged all Launch PRs last year but they are not showing - see all closed PRs on [this list](https://github.com/CodeYourFuture/curriculum/pulls?q=is%3Apr+launch+is%3Aclosed)

**What is wrong with this content?**
It is not showing on the curriculum (see screenshot)
![image](https://github.com/CodeYourFuture/curriculum/assets/80272258/cfe76e3a-3da2-4575-ace9-c5b304e843d0)

**How could this be fixed?**
Worst case scenario I can do all PRs again, but I would like us to investigate why they disappeared in the first place

**Link to content**
https://cyf-curriculum.netlify.app/the-launch/sprints/1/prep/

**Additional context**

**Who else might need to know about this?**

**Comment by SallyMcGrath** [comment]
I'm fixing this now.

While I'm looking at this, I think it makes sense to put the entry criteria in the prep for the module, like we did for Portfolio.

Shall I add it from the linked document now?
