### ISSUE TITLE
"No response" shows up from issue template responses

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#59]
**Describe the bug**

https://cyf-curriculum.netlify.app/fundamentals/sprints/1/backlog/ first exercise has "No response" output from issue template

<img width="773" alt="Screenshot 2023-06-11 at 13 43 01" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/d3da7739-29ca-4cf8-b236-b2d215e765c3">

We should edit out any "No response" sections from GitHub issues. In this instance, I edited it in https://github.com/CodeYourFuture/Course-Fundamentals/issues/8 but it doesn't seem to update on the site. Not sure if there's some caching going on we need to flush...

**Comment by SallyMcGrath** [comment]
It will update - the cache is quite long - maybe 24h.

**Comment by 40thieves** [comment]
To me it seems like we should fail the build if we get a bad response from Github? It may not be obvious if or where content is missing in this scenario - and we might not trigger a new build to (potentially) fix it for days/weeks.

However I recognise that might not be possible currently. I assume that throwing an error (or whatever Go's equivalent is) would fail the build? Can this be done from within a template? Would we need to migrate to a Hugo module (I think that's what they're called? I now can't find the relevant docs page 🙄) for this to work?

**Comment by illicitonion** [comment]
> if we get a bad response from Github? It may not be obvious if or where content is missing in this scenario

Just to make sure we're talking about the same thing, the issue isn't that GitHub is failing a request, it's that when someone crated an issue, they did so using a form template, and if you don't answer one of the form template's questions, GitHub still includes the heading for the field, but says _No response_ in the issue.

So content won't be _missing_, it's just a bit messy/misleading on the page.

---

We could search for this in responses from GitHub and fail the build to tell the person doing the build "You should go edit the GitHub issue text and try again" - I just made the edit locally to do this, and got the following list of included issues which have `_No response_` in their body:

<details>
<summary>(118 issues)</summary>

https://github.com/CodeYourFuture/Induction/issues/1
https://github.com/CodeYourFuture/Induction/issues/2
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/1
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/10
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/11
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/12
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/15
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/16
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/17
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/18
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/19
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/2
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/20
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/21
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/22
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/25
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/26
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/27
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/28
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/29
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/30
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/31
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/5
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/7
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/9
https://github.com/CodeYourFuture/Module-JS1/issues/1
https://github.com/CodeYourFuture/Module-JS1/issues/10
https://github.com/CodeYourFuture/Module-JS1/issues/11
https://github.com/CodeYourFuture/Module-JS1/issues/12
https://github.com/CodeYourFuture/Module-JS1/issues/13
https://github.com/CodeYourFuture/Module-JS1/issues/14
https://github.com/CodeYourFuture/Module-JS1/issues/15
https://github.com/CodeYourFuture/Module-JS1/issues/16
https://github.com/CodeYourFuture/Module-JS1/issues/17
https://github.com/CodeYourFuture/Module-JS1/issues/18
https://github.com/CodeYourFuture/Module-JS1/issues/19
https://github.com/CodeYourFuture/Module-JS1/issues/2
https://github.com/CodeYourFuture/Module-JS1/issues/20
https://github.com/CodeYourFuture/Module-JS1/issues/21
https://github.com/CodeYourFuture/Module-JS1/issues/22
https://github.com/CodeYourFuture/Module-JS1/issues/23
https://github.com/CodeYourFuture/Module-JS1/issues/31
https://github.com/CodeYourFuture/Module-JS1/issues/32
https://github.com/CodeYourFuture/Module-JS1/issues/33
https://github.com/CodeYourFuture/Module-JS1/issues/34
https://github.com/CodeYourFuture/Module-JS1/issues/35
https://github.com/CodeYourFuture/Module-JS1/issues/4
https://github.com/CodeYourFuture/Module-JS1/issues/5
https://github.com/CodeYourFuture/Module-JS1/issues/6
https://github.com/CodeYourFuture/Module-JS1/issues/7
https://github.com/CodeYourFuture/Module-JS1/issues/8
https://github.com/CodeYourFuture/Module-JS1/issues/9
https://github.com/CodeYourFuture/Module-JS2/issues/11
https://github.com/CodeYourFuture/Module-JS2/issues/12
https://github.com/CodeYourFuture/Module-JS2/issues/13
https://github.com/CodeYourFuture/Module-JS2/issues/14
https://github.com/CodeYourFuture/Module-JS2/issues/15
https://github.com/CodeYourFuture/Module-JS2/issues/16
https://github.com/CodeYourFuture/Module-JS2/issues/17
https://github.com/CodeYourFuture/Module-JS2/issues/18
https://github.com/CodeYourFuture/Module-JS2/issues/19
https://github.com/CodeYourFuture/Module-JS2/issues/20
https://github.com/CodeYourFuture/Module-JS2/issues/21
https://github.com/CodeYourFuture/Module-JS2/issues/22
https://github.com/CodeYourFuture/Module-JS2/issues/23
https://github.com/CodeYourFuture/Module-JS2/issues/27
https://github.com/CodeYourFuture/Module-JS2/issues/28
https://github.com/CodeYourFuture/Module-JS2/issues/29
https://github.com/CodeYourFuture/Module-JS2/issues/30
https://github.com/CodeYourFuture/Module-JS2/issues/31
https://github.com/CodeYourFuture/Module-JS2/issues/32
https://github.com/CodeYourFuture/Module-JS2/issues/33
https://github.com/CodeYourFuture/Module-JS2/issues/34
https://github.com/CodeYourFuture/Module-JS2/issues/35
https://github.com/CodeYourFuture/Module-JS2/issues/36
https://github.com/CodeYourFuture/Module-JS2/issues/4
https://github.com/CodeYourFuture/Module-JS2/issues/5
https://github.com/CodeYourFuture/Module-JS2/issues/6
https://github.com/CodeYourFuture/Module-JS2/issues/7
https://github.com/CodeYourFuture/Module-JS2/issues/8
https://github.com/CodeYourFuture/Module-JS2/issues/9
https://github.com/CodeYourFuture/Module-Node/issues/1
https://github.com/CodeYourFuture/Module-Node/issues/10
https://github.com/CodeYourFuture/Module-Node/issues/11
https://github.com/CodeYourFuture/Module-Node/issues/12
https://github.com/CodeYourFuture/Module-Node/issues/13
https://github.com/CodeYourFuture/Module-Node/issues/14
https://github.com/CodeYourFuture/Module-Node/issues/19
https://github.com/CodeYourFuture/Module-Node/issues/2
https://github.com/CodeYourFuture/Module-Node/issues/20
https://github.com/CodeYourFuture/Module-Node/issues/21
https://github.com/CodeYourFuture/Module-Node/issues/3
https://github.com/CodeYourFuture/Module-Node/issues/4
https://github.com/CodeYourFuture/Module-Node/issues/5
https://github.com/CodeYourFuture/Module-Node/issues/6
https://github.com/CodeYourFuture/Module-Node/issues/7
https://github.com/CodeYourFuture/Module-Node/issues/8
https://github.com/CodeYourFuture/Module-Node/issues/9
https://github.com/CodeYourFuture/Module-React/issues/1
https://github.com/CodeYourFuture/Module-React/issues/10
https://github.com/CodeYourFuture/Module-React/issues/11
https://github.com/CodeYourFuture/Module-React/issues/12
https://github.com/CodeYourFuture/Module-React/issues/13
https://github.com/CodeYourFuture/Module-React/issues/14
https://github.com/CodeYourFuture/Module-React/issues/15
https://github.com/CodeYourFuture/Module-React/issues/16
https://github.com/CodeYourFuture/Module-React/issues/17
https://github.com/CodeYourFuture/Module-React/issues/18
https://github.com/CodeYourFuture/Module-React/issues/2
https://github.com/CodeYourFuture/Module-React/issues/20
https://github.com/CodeYourFuture/Module-React/issues/21
https://github.com/CodeYourFuture/Module-React/issues/3
https://github.com/CodeYourFuture/Module-React/issues/4
https://github.com/CodeYourFuture/Module-React/issues/5
https://github.com/CodeYourFuture/Module-React/issues/6
https://github.com/CodeYourFuture/Module-React/issues/7
https://github.com/CodeYourFuture/Module-React/issues/8
https://github.com/CodeYourFuture/Module-React/issues/9
</details>

I think if we're going to do this, though, we need a plan for avoiding people creating issues with this text, because I suspect we'll easily miss the deployment fail-looping on Netlify because of an issue creation causing problems.

Relatedly... What's our plan to ensure we force re-builds when new issues are filed @SallyMcGrath?

**Comment by SallyMcGrath** [comment]
"What's our plan to ensure we force re-builds when new issues are filed @SallyMcGrath?"

repeating conversation  here to log it:  On rebuilds, actually my general plan was just to build once a day and not worry too much about it. I guess on some level I don't want to build in expectation of instantaneous results. :joy:

response: pr from Daniel #90

**Comment by SallyMcGrath** [comment]
> I think if we're going to do this, though, we need a plan for avoiding people creating issues with this text, because I suspect we'll easily miss the deployment fail-looping on Netlify because of an issue creation causing problems.

Is the answer to this a github action or something? It isn't a Big Deal but I agree it's nicer to not have the no response text.

We could do it post hoc on our side but I think it will be fragile.

**Comment by illicitonion** [comment]
Sounds good - I'll leave this open until I do a blitz of editing the 118 issues and turn the warning into a hard error :)
