### ISSUE TITLE
Links from GitHub issues seem to get spurious whitespace put around them

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#60]
**Describe the bug**

On https://cyf-curriculum.netlify.app/fundamentals/sprints/1/backlog/ in the "CYF Blocks" backlog item, the "CYF Blocks" link appears to have spurious whitespace before and after the link, and the "Buttons, inputs and clicks: a todo list" link has spurious whitespace after it. These aren't present in [the original issue](https://github.com/CodeYourFuture/Course-Fundamentals/issues/2).

<img width="725" alt="Screenshot 2023-06-11 at 13 45 37" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/62ea94d8-f012-4d65-9ae8-42cf8c0ae2de">

**Comment by SallyMcGrath** [comment]
So they do... Did I create this with my linkification I wonder? I will look

**Comment by SallyMcGrath** [comment]
Possibly related to #76
