### ISSUE TITLE
Missing step from prep of React Module

### ISSUE THREAD

**Issue by areebsattar** [CodeYourFuture/curriculum#604]
**Describe the bug**
The instructions to set up the React app on the system are not entirely correct as it is missing one of the terminal commands and if you follow the steps the terminal will give an error
sh: vit: command not found

**What is wrong with this content?**
Following it from the prep page results in the failure of the react app running 

**How could this be fixed?**
We can fix this just by adding "npm install" Command in between the 2 commands already provided in the last section of the 2nd page of prep where it asks to Change into the new directory and start the development server:

**Link to content**
https://curriculum.codeyourfuture.io/react/prep/#check-you-can-create-a-react-app-with-vite:~:text=Change%20into%20the%20new%20directory%20and%20start%20the%20development%20server%3A

**Additional context**
N/A
**Who else might need to know about this?**
Volunteers and trainees

**Comment by SallyMcGrath** [comment]
Really great, @areebsattar ! Thank you so much!
