### ISSUE TITLE
Module-React/[TECH ED] Review solutions for TV show project - Coursework link: ERROR 404

### ISSUE THREAD

**Issue by PERicci** [CodeYourFuture/curriculum#607]
**Describe the bug**
The link provided in the [TECH ED] Review solutions for TV show project issue redirects to a non-existent page, resulting in a 404 error.

**What is wrong with this content?**
The page linked to does not exist.

**How could this be fixed?**
Update the link to the correct page, or provide alternative instructions or resources if the content cannot be located.

**Link to content**
Issue: https://github.com/CodeYourFuture/Module-React/issues/14

**Comment by SallyMcGrath** [comment]
Thanks for this . It's actually pointing out a different issue. It exists but you don't have access to it. 

I'll give your team @CodeYourFuture/nw6 access now
