### ISSUE TITLE
Fundamentals Week 1 Backlog: "Share your solution" is too vague

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#61]
**Describe the bug**

On https://cyf-curriculum.netlify.app/fundamentals/sprints/1/backlog/ from [this issue](https://github.com/CodeYourFuture/Course-Fundamentals/issues/2):

<img width="306" alt="Screenshot 2023-06-11 at 13 48 08" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/82f300cb-91f6-415a-ba20-9063cb653673">

"Share your solution" is a bit vague for this being the first time we've asked our trainees to do this. Share your solution with whom? Where?

It should maybe say something like "Share your solution with your cohort on your cohort's Slack channel" or whatever else we expect people to do. (I don't think this needs to happen _every_ week, but the first time we ask, we should be super clear).

**Comment by SallyMcGrath** [comment]
Yes, please go and edit it TY!

**Comment by illicitonion** [comment]
Done!
