### ISSUE TITLE
React Module | [TECH ED] React challenges Sprint 2 and 3 | Incorrect Level Descriptions

### ISSUE THREAD

**Issue by PERicci** [CodeYourFuture/curriculum#610]
**Describe the bug**
Reading the descriptions of challenges in Sprints 2 and 3, I noticed that all challenges are labeled as level 1, similar to those in Sprint 1.

**What is wrong with this content?**
As these challenges belong to sprints 2 and 3 respectively, the labels should reflect their correct levels.

**How could this be fixed?**
Check the correct levels for each challenges in their suitable sprint and change accordaly.

**Link to content**
https://github.com/CodeYourFuture/Module-React/issues/16
https://github.com/CodeYourFuture/Module-React/issues/17

**Comment by SallyMcGrath** [comment]
OK fixed! Thanks @PERicci you are a treasure! 💝
