### ISSUE TITLE
Documentation blockers to making a new site using template

### ISSUE THREAD

**Issue by jessicarose** [CodeYourFuture/curriculum#613]
**Describe the bug**
In following the instructions [here ](https://github.com/CodeYourFuture/curriculum/blob/main/README.md) there are some gaps in documentation that made it impossible to get new site running with instructions given.

The instructions specify running npm i, when the generated hugo site has no package.json file. Should we be making our own or copying it over from org-cyf?

We’re instructed to run ./create-module.sh <NAME, create-module.sh is documented in the base folder when it's in the `tooling` folder

- Errors when running base site using a copied package.json:

```
ERROR render of "taxonomy" failed: "/Users/ramonh/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!code!your!future/curriculum/common-theme@v0.0.0-20240228223757-4757d3862a5d/layouts/_default/baseof.html:7:6": execute of template failed: template: _default/list.html:7:6: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "/Users/ramonh/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!code!your!future/curriculum/common-theme@v0.0.0-20240228223757-4757d3862a5d/layouts/partials/head.html:39:69": execute of template failed: template: partials/head.html:39:69: executing "partials/head.html" at <resources.Concat>: error calling Concat: must provide one or more Resource objects to concat
ERROR render of "page" failed: "/Users/ramonh/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!code!your!future/curriculum/common-theme@v0.0.0-20240228223757-4757d3862a5d/layouts/_default/baseof.html:7:6": execute of template failed: template: _default/single.html:7:6: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "/Users/ramonh/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!code!your!future/curriculum/common-theme@v0.0.0-20240228223757-4757d3862a5d/layouts/partials/head.html:39:69": execute of template failed: template: partials/head.html:39:69: executing "partials/head.html" at <resources.Concat>: error calling Concat: must provide one or more Resource objects to concat
ERROR render of "section" failed: "/Users/ramonh/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!code!your!future/curriculum/common-theme@v0.0.0-20240228223757-4757d3862a5d/layouts/_default/baseof.html:7:6": execute of template failed: template: _default/module.html:7:6: executing "_default/module.html" at <partial "head.html" .>: error calling partial: "/Users/ramonh/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!code!your!future/curriculum/common-theme@v0.0.0-20240228223757-4757d3862a5d/layouts/partials/head.html:39:69": execute of template failed: template: partials/head.html:39:69: executing "partials/head.html" at <resources.Concat>: error calling Concat: must provide one or more Resource objects to concat
Built in 104 ms
Error: error building site: render: failed to render pages: render of "section" failed: "/Users/ramonh/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!code!your!future/curriculum/common-theme@v0.0.0-20240228223757-4757d3862a5d/layouts/_default/baseof.html:7:6": execute of template failed: template: _default/list.html:7:6: executing "_default/list.html" at <partial "head.html" .>: error calling partial: "/Users/ramonh/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/!code!your!future/curriculum/common-theme@v0.0.0-20240228223757-4757d3862a5d/layouts/partials/head.html:39:69": execute of template failed: template: partials/head.html:39:69: executing "partials/head.html" at <resources.Concat>: error calling Concat: must provide one or more Resource objects to concat
```

**What is wrong with this content?**

**How could this be fixed?**

We would need a reproducible set of instructions to make a new site from scratch, ideally in README.md

Or, if someone from the team is able to go through the process with us, we would be so excited to update the documentation and create a video walkthrough of the process once we understand it.

**Link to content**

**Additional context**

**Who else might need to know about this?**

**Comment by SallyMcGrath** [comment]
Hello!  #469 the struggle is real. 

I'd love to go through this with you  - but who are you?! Lovely to meet you!

**Comment by jessicarose** [comment]
Sally hello, sorry to be so rude and not introduce myself! I'm Jess Rose.

I run a free online web and JS bootcamp the Bad Website Club and we've been looking for a learning guide template that might be a good fit for presenting information to our learners in. I ran into @illicitonion at FOSDEM who suggested I check out your platform and when I got a little stuck I wanted to offer to contribute documentation fixes back but was blocked by my lack of understanding.

**Comment by SallyMcGrath** [comment]
👋  So lovely to meet you! We just moved everything around last month so you find us a little bit in disarray! 

Would it be helpful for me to create a blank site people can copy? Also if you want to chat through setup,  could you [book a quick call](https://calendar.google.com/calendar/appointments/AcZssZ05mBuxuAtgX0NrNJYIJcWXMtvWVidqgjD8reE=)? I need to work on documentation for this platform this month so it would be pretty useful for me to go through it with someone who has no context. Let me know if you have time

**Comment by jessicarose** [comment]
That would be a joy, if I could see a blank site it would really help with better understanding what goes well. 

If it's ok, I'll use it to create a guide for "how to fork and edit this framework" both based on and that I can use to contribute back to project documentation.

I'll book a call with you now, thank you so much.

**Comment by SallyMcGrath** [comment]
#469 https://common.codeyourfuture.io/
