### ISSUE TITLE
How to use our curriculum: self educate

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#620]
**Which module(s) and week(s) are you updating?**
Module(s): How to use our curriculum
Week(s): 1 - self educate

## Context

Our curriculum is a highly-structured mapping of resources that enables us to:
- self educate
- self coordinate
- self evaluate

As such, the curriculum is a complex object. It contains structured sequences of works, day plans, links to important resources like workshops and backlogs, reminders about upcoming milestones etc.

## Proposed solution
We need a module that educates our community in how the curriculum works.

Rewriting a week in the curriculum will often involve updating different sections of the curriculum, including the backlog and workshops. You can use this issue to organise the different changes in the curriculum content for a week at CYF.

## Sub-issues 🎫 

- [x] #621

### Tidy and condense 🧹 

- [x] #624

### Day plan

- [x] #622

### Workshop

- [x] #626
 
### Backlog 🎟️ 

- [ ] #623

**Who might need to know about this change?**

**Comment by kfklein15** [comment]
Hi @Dedekind561 , a late feedback, but this shouldn't be a ticket, but the description on the [Milestone](https://github.com/CodeYourFuture/curriculum/milestone/14). My suggestion would be closing it, since it is repeating what we can see on the Milestone :)

**Comment by Dedekind561** [comment]
Yeah good catch - can already see all these issues under the milestone view
