### ISSUE TITLE
Identify and update links to How the curriculum works module

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#628]
## Acceptance criteria

- [x] Identify all comms relevant to new volunteers (e.g. emails, presentations etc)
- [ ] Remove reference to old syllabus and link to new module on the curriculum website

Including presentations like this: https://docs.google.com/presentation/d/1B-fgMuZ3wSHFdCnzXrtF0qxvQc07QkcL3OJr0RGC4og/edit#slide=id.g17dc9a1f019_0_269

### Owner
@Dedekind561 

### Stakeholder
@lilianabermudes @MarianaVazquezCYF

### Approver
@CodeYourFuture/global-syllabus

**Comment by haldenb** [comment]
onboarding steps including all presentations https://docs.google.com/document/d/11YoZbTasrQb6lCcDQUSBbpIFr2ruKhGWiefiBDIL9wM/edit

WIP new Presentation https://docs.google.com/presentation/d/1rawXCCKbTj7t0Em48X1vxw3PxSYsVLYwAxDqsOgHsVU/edit#slide=id.g141ca3155bf_0_11

Let me know if you need a moment for me to walk you through anything :)

**Comment by SallyMcGrath** [comment]
looks abandoned
