### ISSUE TITLE
Fundamentals Week 1: Backlog ordering

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#63]
**Describe the bug**

The backlog lists three items, in order:
1. Learning to learn
2. CYF Blocks
3. Code.org

But the CYF Blocks work _depends_ on the Code.org work.

Rendering them in this order is probably misleading. While teaching people "you need to think about the dependencies between tasks" is useful, at this stage in the course, it's probably a bit much to expect people with so little context of the two tasks to realise the dependency and swap them.

I think we should either:
1. Swap the order of these tasks in the page
2. Explicitly call out in the CYF Blocks issue that it depends on the Code.org issue, and the Code.org issue should be tackled first (and use it as a useful learning moment to tell the trainees explicitly "Sometimes dependencies won't be as obvious as we've called out, consider ordering and dependencies when planning your work")

**Comment by SallyMcGrath** [comment]
This is an interesting point. 

I think maybe 2? It's organised for them on their planner in the right order, but we should probably say explicitly.

Further, though, if you want a fixed field on the issue form, that form lives here:
https://github.com/CodeYourFuture/Course-Fundamentals/blob/main/.github/ISSUE_TEMPLATE/tech-ed-assignment.yml

(and in the Template https://github.com/CodeYourFuture/Module-Template/blob/main/.github/ISSUE_TEMPLATE/tech-ed-assignment.yml )

**Comment by illicitonion** [comment]
Added an edit to https://github.com/CodeYourFuture/Course-Fundamentals/issues/2 to call out the dependency.
