### ISSUE TITLE
Layout: Unaligned time

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#64]
**Describe the bug**

On https://cyf-curriculum.netlify.app/fundamentals/sprints/1/day-plan/ the timestamps aren't all aligned the same. Feels like they probably should be?

<img width="437" alt="Screenshot 2023-06-11 at 14 00 22" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/f0a74af7-f1ea-47a7-a381-e69076fdb790">

**Comment by SallyMcGrath** [comment]
related to #68
