### ISSUE TITLE
PD content ingestor adds zero-width spaces

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#65]
**Describe the bug**

https://github.com/CodeYourFuture/CYF-PD/blob/main/content/blocks/fundamentals-test/readme.md contains a bunch of \uFEFF zero-width non-breaking space characters (e.g. in each "Part 1", "Part 2", etc heading between the "P" and "art").

Not sure why they're there or how they got there, but we should probably remove them, and fix the ingestor to either not add them, or proactively remove them.

**Comment by SallyMcGrath** [comment]
I think this is decap not us, and I think it's likely this issue: https://github.com/decaporg/decap-cms/issues/6602 

They don't seem super moved to fix it, so we need to decide if we want to fork decap and fix it. In any case does this issue need to move to https://github.com/CodeYourFuture/CYF-PD ?
