### ISSUE TITLE
Fundamentals Week 1: Consider linking not embedding CYF Blocks

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#66]
**Describe the bug**

On https://cyf-curriculum.netlify.app/fundamentals/sprints/1/day-plan/ in the CYF Blocks section, we embed the whole CYF blocks interface in the page. It's pretty large, and requires scrolling around the iframe. I'd consider linking to the website and suggesting people open it, rather than embedding it.

**Comment by SallyMcGrath** [comment]
Change it to how you want it imo. 

Try it in a details before rm it altogether?
