### ISSUE TITLE
All search result titles show "404 CYF Curriculum"

### ISSUE THREAD

**Issue by FridIsar** [CodeYourFuture/curriculum#693]
**Describe the bug**

When searching for anything on the search bar, results are displayed but the tittle is "404 CYF Curriculum" (see image)

<img width="1000" alt="image" src="https://github.com/CodeYourFuture/curriculum/assets/45432213/b751d318-a8b5-4cc6-99bc-20a82cad1104">

**How could this be fixed?**

As this behaviour wasn't present in previous iterations, this could be fixed by identifying and reviewing the changes that were made to the search feature.

**Link to content**

Any page.

**Comment by SallyMcGrath** [comment]
fixed in #723
