### ISSUE TITLE
Create PR Guide link is broken

### ISSUE THREAD

**Issue by esma-g** [CodeYourFuture/curriculum#694]
**Describe the bug**
The links to create PR guide directs to an empty page with 404 page not found error.

**What is wrong with this content?**
The link is broken.

**How could this be fixed?**
The link should be updated.

**Link to content**
https://curriculum.codeyourfuture.io/guides/create-a-pull-request/

The link is referred to in several places across the curriculum website and Github:
e.g.
1. https://github.com/CodeYourFuture/HTML-CSS-Module-Project?tab=readme-ov-file
2. https://curriculum.codeyourfuture.io/html-css/sprints/1/prep/#bikes-for-refugees

**Additional context**
n/a

**Who else might need to know about this?**
n/a

**Comment by SallyMcGrath** [comment]
Hi @esma-g . Thanks for this.

Can you let us know where you accessed this link? Where is this link linked? ;)

**Comment by esma-g** [comment]
Hi Sally. Just updated the bug description with the following:

The link is referred to in several places across the curriculum website and Github:
e.g.

https://github.com/CodeYourFuture/HTML-CSS-Module-Project?tab=readme-ov-file
https://curriculum.codeyourfuture.io/html-css/sprints/1/prep/#bikes-for-refugees

**Comment by SallyMcGrath** [comment]
Thanks @esma-g ! Super helpful
