### ISSUE TITLE
Week 1 duplicate labels in database module

### ISSUE THREAD

**Issue by kayali436** [CodeYourFuture/curriculum#703]
**Describe the bug**

 When you type week 1 in labels  there are 2 issues in separate section on board I have sent links below.
**What is wrong with this content?**

**How could this be fixed?**

The issue can be resolved when all issues are in week 1 and there is no duplicate of week 1.
**Link to content**

<img width="996" alt="Screenshot 2024-04-20 at 15 56 57" src="https://github.com/CodeYourFuture/curriculum/assets/79542167/9c3f67e0-fb37-4992-8273-166f71f2e3c5">

<img width="1440" alt="Screenshot 2024-04-20 at 16 03 54" src="https://github.com/CodeYourFuture/curriculum/assets/79542167/56429c33-653d-446c-947a-3e7802b0c9fe">

**Additional context**

**Who else might need to know about this?**
WM5 trainees

**Comment by SallyMcGrath** [comment]
Thanks. Fixed by deleting the duplicate label
