### ISSUE TITLE
Inconsistent labelling of coursework issues by module

### ISSUE THREAD

**Issue by JayMayer** [CodeYourFuture/curriculum#705]
**Describe the bug**

Not all coursework backlog issues have a label corresponding to their module.

**What is wrong with this content?**

When a trainee clones an issue to their own Coursework Planner repository, the link back to the module repo is lost. Without being able to fall back on labels, this means that:

1. Trainees/reviewers can't reliably filter issues based on the module
2. Programmatic analysis of coursework by module is impossible

**How could this be fixed?**

Applying the existing module labels to all issues consistently, with some new labels where not yet created.

**Link to content**

- 0 issues in scope in Fundamentals
- [In scope issues in Induction](https://github.com/CodeYourFuture/Induction/issues?q=is%3Aissue+-label%3A%22%F0%9F%93%85+Induction%22+is%3Aopen+)
- [In scope issues in HTML-CSS](https://github.com/CodeYourFuture/Module-HTML-CSS/issues?q=is%3Aissue+is%3Aopen+-label%3A%22%F0%9F%93%85+HTML-CSS%22+)
- [In scope issues in JS1](https://github.com/CodeYourFuture/Module-JS1/issues?q=is%3Aissue+is%3Aopen+-label%3A%22%F0%9F%93%85+JS1%22+)
- [In scope issues in JS2](https://github.com/CodeYourFuture/Module-JS2/issues?q=is%3Aissue+is%3Aopen+-label%3A%22%F0%9F%93%85+JS2%22+)
- [In scope issues in JS3](https://github.com/CodeYourFuture/Module-JS3/issues?q=is%3Aissue+is%3Aopen+-label%3A%22%F0%9F%93%85+JS3%22+)
- [In scope issues in React](https://github.com/CodeYourFuture/Module-React/issues?q=is%3Aissue+-label%3A%22%F0%9F%93%85+React%22+is%3Aopen+)
- [In scope issues in Servers](https://github.com/CodeYourFuture/Module-Servers/issues?q=is%3Aissue+is%3Aopen+-label%3A%22%F0%9F%93%85+Servers%22)
- [In scope issues in Databases](https://github.com/CodeYourFuture/Module-Databases/issues?q=is%3Aissue+is%3Aopen+-label%3A%22%F0%9F%93%85+Databases%22+)
- [In scope issues in Cloud](https://github.com/CodeYourFuture/Module-Cloud/issues?q=is%3Aissue+is%3Aopen+-label%3A%22%F0%9F%93%85+Cloud%22+) - this label isn't created yet, proposing "📅 Cloud" to be consistent with other modules
- [In scope issues in Launch](https://github.com/CodeYourFuture/Module-The-Launch/issues?q=is%3Aissue+is%3Aopen+-label%3A%22%F0%9F%93%85+Launch%22) - this label isn't created yet, proposing "📅 Launch" to be consistent with other modules

**Additional context**

Fixing this bug could open the door to some interesting automated analysis of coursework by module.

**Who else might need to know about this?**

N/A

**Comment by kfklein15** [comment]
I have updated all the labels on all coursework on every module. Thanks for raising this, Jay.
