### ISSUE TITLE
Fundamentals Sprint 1 Success: Missing learning objectives

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#73]
**Describe the bug**

https://cyf-curriculum.netlify.app/fundamentals/sprints/1/success/ currently shows some slightly odd content:

<img width="608" alt="Screenshot 2023-06-11 at 20 20 17" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/fb19553c-4370-4855-9d89-62f7730d8aed">

Things of note:
1. There are more leaning objectives in the day-plan (e.g. from the code.org exercise), but only one on the page (from the code of conduct exercise)
2. I'm not sure what the "Importance of Professional Development" and "Let's talk about our Code of Conduct" links are doing on this page
3. I'd _maybe_ drop the word "compiled" from the heading, while it's accurate, I'm not sure how helpful it is.

**Comment by illicitonion** [comment]
https://cyf-curriculum.netlify.app/fundamentals/sprints/2/success/ appears to also be missing some LOs

**Comment by illicitonion** [comment]
https://cyf-curriculum.netlify.app/fundamentals/sprints/3/success/ has 0 LOs.

**Comment by illicitonion** [comment]
https://cyf-curriculum.netlify.app/fundamentals/success/ is definitely missing a bunch too.

**Comment by SallyMcGrath** [comment]
I'd like to do the refactor we discussed in #89 first so can we move on that?

**Comment by SallyMcGrath** [comment]
Seems like it's the local module block that isn't grabbing its objectives

**Comment by SallyMcGrath** [comment]
Fixed by #114
