### ISSUE TITLE
Piscine: Set functional skills / maths requirements and identify partners

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#735]
Identify functional skills and partners to obtain free stuff - at least 5 potential partners (June 7th)

**Comment by Dedekind561** [comment]
https://docs.google.com/document/d/17q8U3UwKNjf717o1Gwg5hD4Wm1oSC62tFIf29AoahfQ/edit#heading=h.j2qca2jk7pg5
