### ISSUE TITLE
Piscine: project contributing criteria

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/curriculum#736]
Establish project contributing criteria! What are the rubrics? What does success look like? - E.g. no auth! 
 
 Example of previously developed criteria:
 
 https://github.com/CodeYourFuture/immersive-go-course/blob/main/CONTRIBUTING.md

**Comment by SallyMcGrath** [comment]
Put all this in the Piscine repo https://github.com/CodeYourFuture/The-Piscine/

The readmes are being pulled on to the relevant day plan in the new curriculum view

**Comment by illicitonion** [comment]
This now lives in https://github.com/CodeYourFuture/The-Piscine/blob/main/new-project-guidelines.md
