### ISSUE TITLE
Clone button on backlog goes to 404

### ISSUE THREAD

**Issue by fcaroline2020** [CodeYourFuture/curriculum#757]
**Describe the bug**

Course work copier not working correctly. 

**What is wrong with this content?**

When clicking the 'clone' button in the ITP syllabus backlog, Barath and I receive a 404 (works for Ali). 

**How could this be fixed?**

**Link to content**
https://cyf-programming.netlify.app/api/clone?state=%7b%22issue%22%3a90%2c%22module%22%3a%22Module-User-Focused-Data%22%2c%22prevPath%22%3a%22%2fuser-data%2fsprints%2f1%2fbacklog%2f%22%2c%22sprint%22%3a%22Sprint%201%22%7d

**Additional context**

**Who else might need to know about this?**

**Comment by SallyMcGrath** [comment]
@illicitonion I think this is probably urgent to look into

**Comment by illicitonion** [comment]
https://github.com/CodeYourFuture/curriculum/pull/946 is probably the fix for this

**Comment by illicitonion** [comment]
Yeah, I verified this now works for me. @fcaroline2020 @moneyinthesky can y'all give it a try and make sure it works for you too?
