### ISSUE TITLE
Link render hook sometimes(?) breaks in note shortcodes

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/curriculum#76]
**Describe the bug**

If there is a link within a note shortcode, the `<a>` is malformed and ends up getting split into several `<p>` tags. See this example on the [Fundamentals prep page](https://cyf-curriculum.netlify.app/fundamentals/prep/):

![image](https://github.com/CodeYourFuture/curriculum/assets/424411/6e9ba8ff-f821-40ab-bfef-dc85a1c992a8)

This is perhaps a bad example, as we only intend this URL to be in plain text - actually making it a hyperlink is not helpful.

Playing around with this locally, it seems that converting this to a "normal" link (i.e. `[foo](bar.com)`) is also broken:

![image](https://github.com/CodeYourFuture/curriculum/assets/424411/1eb025a0-254d-4c3f-bea8-316e5b02074a)

What's weird is that on other pages links inside note shortcodes seem to be fine, like [the Code.org exercise in the day plan for Fundamentals week 1](https://cyf-curriculum.netlify.app/fundamentals/sprints/1/day-plan/#code-dot-org) 🤷🏻‍♂️

**How could this be fixed?**

I'm not really very sure - I've poked at this a little bit but I think there's some interaction of Hugo features that I'm not understanding.

**Who else might need to know about this?**

@SallyMcGrath

**Comment by SallyMcGrath** [comment]
hrmmmmm - I wonder if this is because of my wikilinks and therefore related to #60

**Comment by SallyMcGrath** [comment]
This was fixed by #60 but we have a related bug on the youtube tab, which will be fixed in #67

**Comment by SallyMcGrath** [comment]
addressed separately in #121  as I realised I was running through markdown twice in tabs
