### ISSUE TITLE
Fundamentals Sprint 2: Ship It should probably have novel content

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#78]
**Describe the bug**

https://cyf-curriculum.netlify.app/fundamentals/sprints/2/day-plan/ the "Ship it" section seems to be identical to that from sprint 1.

This doesn't seem right - I would have expected our trainees to _update_ their existing repo, rather than create a new one? And the whole "remember your personal home page" section seems very redundant.

Was this intentional?

**Comment by SallyMcGrath** [comment]
Yes, I agree - but it is like this in the old version. Can you update it?
