### ISSUE TITLE
[Content] switch fork your planner video

### ISSUE THREAD

**Issue by fcaroline2020** [CodeYourFuture/curriculum#783]
**Which module(s) and week(s) does this change affect?**
Module(s): 1
Week(s): 1

[Here](https://cyf-programming.netlify.app/user-data/prep/#fork-your-planner)

**What is the work that needs to be done?**

the video seems out of place because trainees would need to click to the next section to get the link and then back to the video to see how to fork, should be switched or embedded in the page [set up planner](https://cyf-programming.netlify.app/user-data/prep/#set-up-planner)

- [ ] the video on how to fork the planner should be moved

**Why is this work important to do?**

**Additional context**

**Who might need to know about this change?**

**Comment by Shubhdeep02** [comment]
Hey @fcaroline2020 I guess it's only for the context in the `fork the planner` section to get the brief idea about forking, following which the next section trainees could actually try it.

**Comment by Shubhdeep02** [comment]
@fcaroline2020 if not then i would try to work on the issue?? is it fine
