### ISSUE TITLE
User Focused Data / Sprint 1 - Clean up objectives

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#788]
- https://cyf-programming.netlify.app/user-data/sprints/1/prep/#version-control
Objectives "Define a repository" and "Explain why we use Github" should probably be moved to the following page

- https://cyf-programming.netlify.app/user-data/sprints/1/prep/#forking-a-repository
Maybe add an objective to "Explain why we might want to fork a repository in Github"

- https://cyf-programming.netlify.app/user-data/sprints/1/prep/#working-locally
Objectives don't look relevant to the material?
Maybe objectives could be "Explain the difference between a fork and a clone", "Explain the difference between local and remote" and "Clone a repository to your local machine"

- https://cyf-programming.netlify.app/user-data/sprints/1/prep/#viewing-files
Missing objectives

- https://cyf-programming.netlify.app/user-data/sprints/1/prep/#branching
Objectives don't look relevant to the material?

**Comment by illicitonion** [comment]
I think a lot of this got covered in https://github.com/CodeYourFuture/curriculum/pull/943 (and https://github.com/CodeYourFuture/curriculum/pull/970)
