### ISSUE TITLE
User Focused Data / Sprint 1 - Clone to CYF folder

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#789]
https://cyf-programming.netlify.app/user-data/sprints/1/prep/#working-locally
Maybe add a reminder to select the CYF folder which was created during prep?

**Comment by SallyMcGrath** [comment]
100%!

Amazingly, this issue with the folder and where files live is a HUGE BLOCKER for trainees at first.

**Comment by fcaroline2020** [comment]
Approved
