### ISSUE TITLE
User Focused Data / Sprint 1 - Clear confusion in exercise 8.1

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#791]
https://cyf-programming.netlify.app/user-data/sprints/1/prep/#branching
In exercise 8.1, step 3 asks the trainee to open the terminal, but the video in step 4 explains how to create a new branch using VSCode shortcuts (not using the terminal).
- How do we feel about asking the user to run `git status` and examining the output?
- How do we feel about asking them to create the branch using `git checkout -b update-blog-1`?

**Comment by SallyMcGrath** [comment]
The issue we've found is that trainees who used to only use the terminal just memorise some commands and don't build the mental model.

We have tried using VSCode first and then using commands in workshops -- expecting both.

**Comment by moneyinthesky** [comment]
> The issue we've found is that trainees who used to only use the terminal just memorise some commands and don't build the mental model.
> 
> We have tried using VSCode first and then using commands in workshops -- expecting both.

Ok, in that case - I might remove the steps to open the terminal in the exercise, as they won't need the terminal to create the branch.

**Comment by fcaroline2020** [comment]
approved 👍
