### ISSUE TITLE
User Focused Data / Sprint 2 - Emphasise asking good questions

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#792]
https://curriculum.codeyourfuture.io/guides/asking-questions is mentioned in different exercises.
This is very important, and so maybe deserves a bigger discussion in the day plan?
We could ask trainees to explain back how to ask questions and also ensure they understand the value in asking good questions (collaborating efficiently, communicating effectively, improving employability).

**Comment by SallyMcGrath** [comment]
there are some workshops here https://github.com/CodeYourFuture/CYF-Workshops/tree/main/asking-questions

**Comment by moneyinthesky** [comment]
Currently, the day plans seem fairly generic - not specific to the material of the current sprint?
Which workshop to run is potentially voted on in Slack.
I wonder if it makes sense to add the workshop @SallyMcGrath mentions in the previous comment (https://github.com/CodeYourFuture/CYF-Workshops/tree/main/asking-questions) directly into the Sprint 1 day plan, or is this just something the volunteers who are delivering ITP should coordinate in Slack.

I guess the bigger question - should we have specific workshop recommendations in specific day plans based on the material being covered? 🤔

**Comment by moneyinthesky** [comment]
The workshop mentioned on this issue is in the Sprint 2 backlog: https://cyf-programming.netlify.app/user-data/sprints/2/backlog/

**Comment by moneyinthesky** [comment]
@fcaroline2020 I think this will be part of your work to more generally add suggested workshops into the Day Plan 😄 
In this case, adding https://github.com/CodeYourFuture/CYF-Workshops/tree/main/asking-questions into User Focused Data / Sprint 2.
