### ISSUE TITLE
User Focused Data / Sprint 1 - Git add, commit, push explanation

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#793]
Some of the backlog submission instructions mention making commits, etc. - however I don't believe we've given any explanation or examples of making changes, adding to git, committing changes, pushing changes, etc.
Maybe we should be going through this in prep? (Although some of that explanation is in https://github.com/CodeYourFuture/Portfolio/blob/Module-HTML-CSS/README.md)

**Comment by SallyMcGrath** [comment]
Oh it's here https://curriculum.codeyourfuture.io/induction/

**Comment by moneyinthesky** [comment]
> Oh it's here https://curriculum.codeyourfuture.io/induction/

Ah, I see -  so this is something for them to figure out, follow the video and potentially try in a workshop with mentor help 👍 I'll close this ticket.
For others who are looking for this on the ITP site, it's here: https://cyf-programming.netlify.app/user-data/sprints/1/prep/#wrapping-up
