### ISSUE TITLE
User Focused Data - Always have lunch at 1pm

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#795]
It probably makes sense to have a consistent time for community lunch.
We could tweak the timings of the sessions happening before lunch so we always land on 1pm.

**Comment by SallyMcGrath** [comment]
Yes, to override the default block times for your own context, add a time property in the day plan block list, like

```
[[blocks]]
name="Morning orientation"
src="blocks/morning-orientation"
time=20
```

**Comment by fcaroline2020** [comment]
Adjusting lunch to be at 1 and retro at 5 @moneyinthesky @SallyMcGrath

**Comment by 40thieves** [comment]
Syllabus team: we think this is done. Closing.
