### ISSUE TITLE
Fundamentals Sprint 3: Prep is missing

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#80]
**Describe the bug**

https://cyf-curriculum.netlify.app/fundamentals/sprints/3/prep/ is empty - it probably shouldn't be (of if it should be, we should probably either remove it from the index, or note that it's intentionally empty).

**Comment by SallyMcGrath** [comment]
@gregdyke could you pick this up?  What should they get done before they come to class on the third week, which is "delivery"

**Comment by kfklein15** [comment]
I most likely have some PD prep to add to this page. Just haven't gotten to that yet.

**Comment by kfklein15** [comment]
Prep [PR](https://github.com/CodeYourFuture/curriculum/pull/94) was merged but build is failing.
Not sure if it's better to revert the PR or create a new one.

**Comment by kfklein15** [comment]
This is now showing correctly in prod: https://cyf-curriculum.netlify.app/fundamentals/sprints/3/prep/
