### ISSUE TITLE
Build and deploy five websites to Netlify with Scrimba including the capstone project step with review.

### ISSUE THREAD

**Issue by ZacheeNiyokwizera** [CodeYourFuture/curriculum#803]
description: This course will teach you HTML and CSS through building and deploying five awesome projects. It is also fully interactive, with over 75 coding challenges. There are no prerequisites, so it is suitable for absolute beginners.
Device: DESKTOP
Instructions:
[Learn HTML & CSS on Scrimba](https://scrimba.com/learn/htmlandcss)

[This course](https://scrimba.com/learn/htmlandcss) will teach you HTML and CSS through building and deploying five awesome projects. It is also fully interactive, with over 75 coding challenges. There are no prerequisites, so it is suitable for absolute beginners. Come to CYF workshops to get help and to work with other applicants on your projects. If you do not have a computer, [find your nearest free online centre](https://www.onlinecentresnetwork.org/ournetwork/find-centre#/map).

Complete a project, and then share the URL here. You will share five links in total for this step. You can move on to the next project as soon as you have shared the link to your last one. You don't need to wait.

Personalise your URLs

Before you share your link with your mentors, edit your Netlify URL to include your name. It can just be your given name or your family name if you prefer. Follow this tutorial to understand how to do this: [Modify your domain name on Netlify](https://www.makeuseof.com/netlify-free-domain-name-modify/)

Complete modules 1-5

Build and deploy your first website now share your link, and move on to...
Build a Google.com clone now share your link, and move on to...
Build a Digital Business card now share your link, and move on to...
Build a Space Exploration site now share your link, and move on to...
Build a Birthday GIFt site now share your link, and unlock the next step.

(The next step will be to build the final project in this course, Hometown Homepage.)

Accessibility

Scrimba uses a specialised video format and captions are not turned on by default. If you are hard of hearing or Deaf, turn on live captions in your browser (Chrome) in Settings > Advanced > Accessibility > [Live Captions](https://support.google.com/chrome/answer/10538231?hl=en-GB) . If you are using a screenreader, please contact us directly for an adaptation.

Show Image Upload: No
Show Motivational Letter: No
Show Submit Url: Yes
Is optional: No
Acceptance Criteria:
I have shared a link to my personal website deployed on Netlify
I have shared a link to my Google.com clone website deployed on Netlify
I have shared a link to my Digital Business Card website deployed on Netlify
I have shared a link to my Space Exploration website deployed on Netlify
I have shared a link to my Birthday GIFt website deployed on Netlify
Each of my links includes my name
Version: 4
Eligibility From Date: 2023-09-01T00:00:00.000Z
Eligibility To Date: 2025-01-11T23:59:59.999Z

**Comment by SallyMcGrath** [comment]
description: Build a solo website and undergo code review.
Device: DESKTOP
Instructions:
[Learn HTML & CSS on Scrimba](https://scrimba.com/learn/htmlandcss)

Complete module 6

Now you will build a real solo project, your Hometown Homepage. When you get stuck, ask questions in our Slack. Bring your work to our workshops and share ideas and approaches.



Personalise your URL


Before you share your link with your mentors, edit your Netlify URL to include your name. It can just be your given name or your family name if you prefer. Follow this tutorial to understand how to do this: [Modify your domain name on Netlify](https://www.makeuseof.com/netlify-free-domain-name-modify/)



Get your code reviewed

[You should not pay for a pro account on Scrimba.](https://scrimba.com/learn/htmlandcss/get-a-code-review-can9rgU3) As a CYF candidate, you are eligible to ask for code review in the CYF Slack.



Join the ITD Slack.
Ask for Code Review. Use this template:


Code Review Request
Hello. I have completed Step 3 of Intro to Digital. I would be grateful if someone could review my code.

Link to my project on GitHub : URL
Link to my project on Netlify : URL




When you have completed all the steps in ITD, participate in our developer community by reviewing code from newer applicants. You must join ITD Slack to complete this step.



Accessibility

Scrimba uses a specialised video format and captions are not turned on by default. If you are hard of hearing or Deaf, turn on live captions in your browser (Chrome) in Settings > Advanced > Accessibility > [Live Captions](https://support.google.com/chrome/answer/10538231?hl=en-GB) . If you are using a screenreader, please contact us directly for an adaptation.
Show Image Upload: Yes
Show Motivational Letter: No
Show Submit Url: Yes
Is optional: No
Acceptance Criteria:
I have shared a link to my Hometown Homepage deployed on Netlify
I have shared a link to my code on GitHub
I have asked for a code review on Slack
I have shared a screenshot of my code review request on Slack
I have responded to that code review on Slack
Version: 4
Eligibility From Date: 2023-09-01T00:00:00.000Z
Eligibility To Date: 2025-01-11T23:59:59.999Z
