### ISSUE TITLE
Fundamentals Sprint 3: LinkedIn task conflicts with Sprint 1 LinkedIn task

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#81]
**Describe the bug**

A couple of things conflict:
1. [Sprint 3's ticket](https://github.com/CodeYourFuture/Course-Fundamentals/issues/13) is called "Join LinkedIn" (I just renamed it to "Start Using LinkedIn" on GitHub, should propagate soon-ish). But Sprint 1 already required our trainees to join LinkedIn.
2. Sprint 3's ticket says "If it's not safe for you to share your name online, you can skip this task." but [Sprint 1's ticket](https://cyf-curriculum.netlify.app/fundamentals/sprints/1/prep/#linkedin) talked about how you should make one regardless but settle on a name you're able to use, whether or not it's your legal name. This seems to be conflicting, and we should make sure we have a more consistent story here.

cc @kfklein15 @esma-g @SallyMcGrath

**Comment by kfklein15** [comment]
For PD we would not ask them to start using Linkedin in Fundamentals, but later. Does Tech Ed think this is important at this point?

@LaraHuzjan

**Comment by illicitonion** [comment]
When would we like them to do each of the following?
1. Make a LinkedIn profile
2. Form a network with their cohort
3. Link to their LinkedIn from their Slack profile
4. Link to their LinkedIn from their GitHub

**Comment by kfklein15** [comment]
This is all planned for other weeks. https://docs.google.com/spreadsheets/d/1bTWa9PTG9p5Q0q5Ux8i5Fxt9YrGKJ_gIKoeKNEurXP4/edit#gid=1367122967

**Comment by SallyMcGrath** [comment]
It's part of the Fundamentals graduation criteria and has been for 2 years.

**Comment by kfklein15** [comment]
But it's not coursework, it's a prep and is already on it.
The other things will be done later in the Syllabus, as I shared a couple of weeks ago.
