### ISSUE TITLE
Create application form for joining the Piscine course

### ISSUE THREAD

**Issue by 40thieves** [CodeYourFuture/curriculum#811]
To apply for the Piscine course (which will act as an assessment for the SDC), we would like trainees to submit a simple form.

The goals of the application form are:

- Build a concrete list of trainees' details
- Provide a "low barrier" to the Piscine. The thinking is that this will act like a basic filter to ensure that Piscine applicants are willing (and organised enough) to fill it out
- ...?

**Comment by 40thieves** [comment]
I've thrown together a quick draft here: https://docs.google.com/forms/d/1qQQmMoB6oHtPnMtAymHJIaIUP-RziCrL-xko0Rg221k/edit (only visible to those logged into CYF google accounts, if that's a problem I can probably copy/paste it somewhere more accessible)

**Comment by SallyMcGrath** [comment]
related to #828
