### ISSUE TITLE
Fundamentals Sprint 3: PD Placeholder

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#83]
**Describe the bug**

Currently Fundamentals Sprint 3 has a placeholder for a PD session at 11:15. We should make sure this is filled in before our first cohort uses this website.

**Comment by kfklein15** [comment]
Do we need a bug for this? We are updating the website little by little - I was on holiday. But if we start having a bug and also our PR to update it, won't we (meaning I) have to manage to double the amount of work?

**Comment by illicitonion** [comment]
Welcome back from holiday 🎉 

I definitely wouldn't advocate for bugs for _every_ piece of missing content!

I filed this one specifically because we're hoping to run WM7 from the new curriculum website in <2 weeks, and I've been doing an audit of Fundamentals to see what blockers we have from being ready to launch - this is basically the only PD blocker for all of Fundamentals, so it'd be great to prioritise if possible!

**Comment by kfklein15** [comment]
Thanks!
Yep, I'll be working on it today or tomorrow. So will close this for now :)
