### ISSUE TITLE
User Focused Data - Sprint 1 - Broken links of different versions of educational backlog

### ISSUE THREAD

**Issue by pseudopilot** [CodeYourFuture/curriculum#834]
**Describe the bug**

In User Focused Data / sprint 1 / Previous Versions
https://cyf-programming.netlify.app/user-data/sprints/1/prep/#previous-versions

all 3 links are broken:

> [Deployed version A educational blog](https://64b6f9a2b9c00a00082bbeeb--git-demo-week1.netlify.app/)
> [Deployed version B educational blog](https://64b6fd80d14d510008aab4aa--git-demo-week1.netlify.app/)
> [Deployed version C educational blog](https://64b971b0adae9e00089d7531--git-demo-week1.netlify.app/)

Last list item references the branch named `mainLive` which doesn't exist. As a result it leads to the page with no commits shown.

> 4. Which commit from the [education-blog](https://github.com/CodeYourFuture/education-blog/commits/mainLive) repo correspond to Version A?

**Who else might need to know about this?**

@SallyMcGrath

**Comment by SallyMcGrath** [comment]
Suggest you fix it! 😉

**Comment by pseudopilot** [comment]
@illicitonion ,
to fix this issue I need the access to editing the repo https://github.com/CodeYourFuture/education-blog to create a few new branches and deploy them.

Would you please help me with obtaining the access?
