### ISSUE TITLE
Fundamentals Sprint 3: Broken link to graduation criteria

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#84]
**Describe the bug**

On https://cyf-curriculum.netlify.app/fundamentals/sprints/3/day-plan/ there's a "met the criteria" link to https://cyf-curriculum.netlify.app/fundamentals/sprints/3/graduation/criteria.md - it links to a 404.

**Comment by SallyMcGrath** [comment]
Where should it go? 

- [ ] In a content block here?
- [ ] In a guide>
- [ ] In the main docs with Trainee Agreement etc https://docs.codeyourfuture.io/organisation/agreements-and-rules/student-agreement
- [ ] In a NEW docs folder in this site 😬 🙅 
- [ ] On an issue on the repo https://github.com/CodeYourFuture/Course-Fundamentals/issues/15 ?

**Comment by illicitonion** [comment]
I think any of those make sense :)

I'd lean towards in the trainee agreement, except that probably makes it the hardest thing to edit (which... Maybe is good? Unclear...)
