### ISSUE TITLE
User Focused Data / Sprint 2 - Prepare for Asking Questions in Backlog

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#850]
Bring the "Prepare for Asking Questions" workshop into User Focused Data / Sprint 2.
https://github.com/CodeYourFuture/Module-HTML-CSS/issues/46

**Comment by moneyinthesky** [comment]
Finished tagging the issue - so it should hopefully appear on [this page](https://cyf-programming.netlify.app/user-data/sprints/2/backlog/) soon.

**Comment by SallyMcGrath** [comment]
To make this show up in your backlog for this module

1. Open the issue in your module repo https://github.com/CodeYourFuture/Module-User-Focused-Data/issues
2. tag it with the label set in your backlog_filter

http://localhost:1313/common-theme/front-matter/#backlog

**Comment by SallyMcGrath** [comment]
@moneyinthesky Just to poke you about this again. I think you've misunderstood something about adding tickets. 

https://common.codeyourfuture.io/common-theme/pages/backlog/
