### ISSUE TITLE
Data Groups / Sprint 1 - Referenced Medium article is member-only

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#857]
The failing fast Medium article referenced here: https://cyf-programming.netlify.app/data-groups/sprints/1/prep/#failing-fast - is now member-only and requires you to have an upgraded Medium account.
We should probably find a freely available alternative.

**Comment by SallyMcGrath** [comment]
That content lives over on the PD curriculum https://cyf-pd.netlify.app/

**Comment by moneyinthesky** [comment]
I'm thinking of using this as a replacement - https://medium.com/@amitonline/failing-fast-embracing-failure-as-a-pathway-to-agile-success-e12a2f9b72cd
Will raise the PR once I'm added as a contributor to CYF-PD

**Comment by moneyinthesky** [comment]
I can see my update reflected here: https://cyf-pd.netlify.app/blocks/fail-fast-prep/
But can't see it on the ITP site yet...

**Comment by SallyMcGrath** [comment]
Oh, er... this might be me, sorry. 

I had to reduce api calls so I mounted this module, but perhaps I didn't finish the work of updating the cms. I will look

**Comment by 40thieves** [comment]
Blocked by @SallyMcGrath: the PD website (which isn't being updated any more) outputs 2 files and we need it to update both, instead of just the README output.
