### ISSUE TITLE
Data Groups / Sprint 1 & 2 - Not clear which exercises to do from Module-Data-Groups

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#858]
Both Sprint 1 and Sprint 2 mention completing exercises in https://github.com/CodeYourFuture/Module-Data-Groups, however it's not clear which exercises from this repo should be completed.
Maybe we can clear this up in the Backlog issues? We might get some ideas from https://github.com/CodeYourFuture/Module-JS2 which I believe is where these exercises originally came from - as it looks like those exercises are already divided by week.

**Comment by pseudopilot** [comment]
@moneyinthesky , it looked very easy to do but eventually I figured out that the task we have in https://github.com/CodeYourFuture/Module-Data-Groups
are not taken from https://github.com/CodeYourFuture/Module-JS2 (as I would expect too) but from:
https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week1
https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week2
https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week3
https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week4
These repos were archived on Jan 14, 2024 and they look to be older than the one which you mentioned (https://github.com/CodeYourFuture/Module-JS2).

So, I just want want to clarify if it is correct and I can group them as they were grouped in that closed repos? Or do we want to include the tasks from https://github.com/CodeYourFuture/Module-JS2 instead?

By the way the tasks from https://github.com/CodeYourFuture/Module-JS2/tree/main/week-3 are almost matching https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week4.
The tasks for the rest of the weeks seem to be absolutely different.

Or maybe @SallyMcGrath can clarify this.

**Comment by SallyMcGrath** [comment]
I intended to combine these 4 4 week modules (plus Induction week, and remove what seemed obvious overflow)

https://github.com/CodeYourFuture/Module-HTML-CSS
https://github.com/CodeYourFuture/Module-JS1/
https://github.com/CodeYourFuture/Module-JS2/
https://github.com/CodeYourFuture/Module-JS3/

and distribute across these 4 3 week modules

https://github.com/CodeYourFuture/Module-User-Focused-Data
https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data
https://github.com/CodeYourFuture/Module-Data-Groups
https://github.com/CodeYourFuture/Module-Data-Flows

**Comment by pseudopilot** [comment]
Thank you for your explanation, @SallyMcGrath . I have reviewed all the repositories you mentioned above, and indeed the tasks from the sources (Module-HTML-CSS, Module-JS1, Module-JS3) match the tasks in the new Modules (Module-User-Focused-Data, Module-Structuring-and-Testing-Data and Module-Data-Flows).

However, Module-JS2 and Module-Data-Groups seem to be out of sync.
I hope this PR fixes it:
https://github.com/CodeYourFuture/Module-Data-Groups/pull/46
