### ISSUE TITLE
Data Groups / Sprint 3 - Duplicate backlog issue?

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#859]
Looks like there's a duplicate issue on https://cyf-programming.netlify.app/data-groups/sprints/3/backlog/ called "[TECH ED] Debug book library". We already have one called "[TECH ED] Build reading list display".

We could just remove "Debug book library" from the Intro to Programming Planner.

**Comment by SallyMcGrath** [comment]
Remove your duplicate issue from your repo, not the planner.
