### ISSUE TITLE
Data Groups / Sprint 3 - Review Backlog Issue Descriptions

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#860]
For the backlog items listed here:
https://cyf-programming.netlify.app/data-groups/sprints/3/backlog/
We should review the descriptions in the backlog issues - as they may need some minor updates after being moved from an older JS2 repo.
For example, this issue https://github.com/CodeYourFuture/Module-Data-Groups/issues/26 - mentions looking in a Sprint-3 directory, but we don't have a Sprint-3 directory in the repo.
Another example is https://github.com/CodeYourFuture/Module-Data-Groups/issues/20 - where we could explicitly mention which directory the exercise is in.

**Comment by pseudopilot** [comment]
The links to the tasks are updated for the following issues:

**Module-Data-Groups**
https://github.com/CodeYourFuture/Module-Data-Groups/issues/7
https://github.com/CodeYourFuture/Module-Data-Groups/issues/8
https://github.com/CodeYourFuture/Module-Data-Groups/issues/18
https://github.com/CodeYourFuture/Module-Data-Groups/issues/20
https://github.com/CodeYourFuture/Module-Data-Groups/issues/26

**Module-Data-Flows**
https://github.com/CodeYourFuture/Module-Data-Flows/issues/21
https://github.com/CodeYourFuture/Module-Data-Flows/issues/24
https://github.com/CodeYourFuture/Module-Data-Flows/issues/25
https://github.com/CodeYourFuture/Module-Data-Flows/issues/31

**Comment by 40thieves** [comment]
Syllabus team: we think this is done. Closing.
