### ISSUE TITLE
Add opportunity for group-work experience

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#898]
One of our ITP requirements is: 
> Gaining experience working in groups to deliver working software (with tests)

In support of this, we can add some work for a small group of trainees to collaborate on. Several potential projects are here: https://github.com/CodeYourFuture/CYF-Group-Projects?tab=readme-ov-file

We'll need to work out where we have space for this in the backlog (which module / which sprint). Further collaboration can take place during the in-person session.

**Comment by moneyinthesky** [comment]
Added these into the Data Groups module. Awaiting feedback.
- [[TECH ED] Group Project: Tic-Tac-Toe - Steps 1 to 6](https://github.com/CodeYourFuture/Module-Data-Groups/issues/49)
- [[TECH ED] Group Project: Tic-Tac-Toe - Steps 6 to 10](https://github.com/CodeYourFuture/Module-Data-Groups/issues/50)

**Comment by 40thieves** [comment]
Syllabus team: we're happy with those, so going to close this out.

**Comment by illicitonion** [comment]
I thought @moneyinthesky was planning on doing a bit more here? As per https://codeyourfuture.slack.com/archives/C076K3V76CA/p1730042418174759 this covers working together well, but doesn't cover breaking down tasks into parallelisible chunks, or handling merge conflicts?
