### ISSUE TITLE
Add TV Show project to Data Flows module

### ISSUE THREAD

**Issue by moneyinthesky** [CodeYourFuture/curriculum#899]
The repo for this project is here: https://github.com/CodeYourFuture/JS3-Module-Project

This is meant to be run in a pair swapping style.
- you complete levels 0 and 100 in your own repo
- you complete level 200 in someone else's repo and raise a PR
- you complete level 300 in your own repo again
- etc.

This should fit - maybe across all 3 sprints - of the Data Flows repo. Maybe the breakdown could be something like this:
- Sprint 1: Levels 0, 100 and 200 - requiring both working on your own code base and another persons
- Sprint 2: Levels 300 and 400 - requiring both working on your own code base and another persons
- Sprint 3: Level 500 (and prepare for a demo?) - just on your own code base

**Comment by moneyinthesky** [comment]
Created and added 3 new backlog issues to be done across the 3 sprints of the Data Flows module:
- https://github.com/CodeYourFuture/Module-Data-Flows/issues/44
- https://github.com/CodeYourFuture/Module-Data-Flows/issues/45
- https://github.com/CodeYourFuture/Module-Data-Flows/issues/46

FYI @CodeYourFuture/itp-syllabus-team

**Comment by SallyMcGrath** [comment]
You also have the option of hosting this in the module in the project view. Here's the old version

https://curriculum.migracode.org/js3/product/

If you'd like that, it's right here https://github.com/Migracode-Barcelona/curriculum/tree/main/content/js3/product
