### ISSUE TITLE
Feature: Highlight sections of a code block

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#9]
Given a code block, 
I want to highlight various parts of the code fence by altering the opacity so to draw a user's attention to a particular section of the code block.

```js
function sum(a,b) {
      return a + b;
}

const result = sum(10,32);
```
Given the code snippet above, I might want to highlight the line with the call site, so the rest of the code block's opacity would need to be lowered so the call site line stands out.

**Comment by 40thieves** [comment]
I guess this is a feature request for CM6 then :D

Pretty sure it can be done via [a line decoration](https://codemirror.net/docs/ref/#view.Decoration%5Eline). It's not entirely clear how we'd pass the configured line numbers through to CM6 though.

**Comment by Dedekind561** [comment]
![image](https://github.com/CodeYourFuture/curriculum/assets/25401570/de3e96fb-17ad-4a79-93b5-9c17d64a4f83)

**Comment by Dedekind561** [comment]
Sorry I missed the earlier part of this thread where you shared exactly the same thing lol 🤦

**Comment by SallyMcGrath** [comment]
Also #118
