### ISSUE TITLE
Tooltip hovers can be overlapped / cropped

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#906]
The "curriculum" tooltip on https://programming.codeyourfuture.io/how-our-curriculum-works/prep/#%25EF%25B8%258F-curriculum doesn't get displayed properly - a bunch of it appears to be cropped, looks like at the borders of neighbouring elements.

<img width="1387" alt="Screenshot 2024-09-13 at 13 18 55" src="https://github.com/user-attachments/assets/19a8a421-049f-482d-bc6a-0a9a0f611b21">

**Comment by SallyMcGrath** [comment]
Oh, doh - this is a z-index bug and it can be fixed very easily. Tiny tweak! Sorry!
