### ISSUE TITLE
Searching for a morning orientation block in a day plan is surprisingly difficult

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#911]
https://programming.codeyourfuture.io/how-our-curriculum-works/sprints/self-coordinate/prep/#morning-orientation sets the task to search for a morning orientation block in a day plan.

In practice, when I tried to do this, I had to "show more" 3-4 times past a long list of Success views with morning orientation blocks in them.

This felt not ideal for what's meant to be a simple task...

**Comment by SallyMcGrath** [comment]
So, let's think through our options

1. we could suppress the success titles from search
1. we could remove the titles from success 👎 
1. we could do a "hide from success" type check on the success view, though we wouldn't put the param on the block itself but on the prep or day plan params, and not show those objectives there
1. we could try to pass the page context through the block system and contextually show the objectives on day plan/prep but not success based on a param in front matter (I can see that 15 months ago I began on this road for some reason, but also that I abandoned it) -- I'm not keen on adding another conditional filter level like this tbh
1. ???

What feels clearest to you?

**Comment by illicitonion** [comment]
I think being able to search for a block that's present in every day plan is probably not a core use-case for the curriculum.

I think there are probably two useful things to do:

1. On this particular page, we should just link to a block, rather than have people search for it. We can introduce "Search for something in the curriculum" as an exercise for something people are more likely to actually search for (e.g. "Grouping data" or "Array" or "Side effects" or something)? This would, however, introduce a per-course difference here (because we can't guarantee that everywhere How Our Curriculum Works is used has the same thing to search for if it's not super generic).
2. We should probably make the headings on the success page be links to where the LOs were collected from - if "Morning orientation" on the success page was a link, at least there's a way to go from the success page to the block (even if I don't think it would be an intuitive way to solve the exercise as currently written).

WDYT?
