### ISSUE TITLE
Do we want to re-organise our CodeWars collections?

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#916]
AFAIK we no longer have modules. like "JS1".

https://www.codewars.com/users/CodeYourFuture/authored_collections is grouped into module-named themes.

We may want to rename or re-group some of these collections.

**Comment by SallyMcGrath** [comment]
The most useful collections on there are

https://www.codewars.com/collections/cyf-array-and-object-methods
https://www.codewars.com/collections/cyf-interview-prep-problems-and-sub-problems
https://www.codewars.com/collections/cyf-handling-falsy

We should probably keep the others until Migracode have chance to copy them over to their own account maybe? We can't just keep adding collections as there's a limit on them (we already had to collapse the weeks into modules for this reason)

**Comment by SallyMcGrath** [comment]
I've renamed the collections to add the CYF module names as well

**Comment by illicitonion** [comment]
Thanks! This is probably done enough to just close.
