### ISSUE TITLE
Clicking in-page anchor links obscures the title of the item being clicked to

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#919]
e.g. going to https://programming.codeyourfuture.io/guides/reviewing/checklist/#edge-cases (e.g. by clicking a link to "Edge Cases") leads to the "Edge Cases" title being hidden behind the header, and the top part of the first paragraph being faded. See screenshot:

<img width="1576" alt="Screenshot 2024-09-16 at 14 55 03" src="https://github.com/user-attachments/assets/a1612950-8d75-4b83-97be-f9a944861229">

Ideally this would be offset so the view on click is more like:

<img width="1546" alt="Screenshot 2024-09-16 at 14 55 22" src="https://github.com/user-attachments/assets/9f8915f7-6752-4675-b7bc-73568cbd6a19">

**Comment by SallyMcGrath** [comment]
![Image](https://github.com/user-attachments/assets/0716b9cd-2f9b-4512-8f9e-a4bb59e2cff1)
