### ISSUE TITLE
How Our Curriculum Works: Clarify which backlog items are intended for volunteers, trainees, or everyone

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#920]
e.g. in https://programming.codeyourfuture.io/how-our-curriculum-works/sprints/self-evaluate/backlog/ the Pair Programming exercise is phrased assuming the person doing it is a volunteer.

**Comment by SallyMcGrath** [comment]
Done this, though I'd like to go over this a bunch
