### ISSUE TITLE
Assessment and Milestones

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#926]
**Which module(s) and week(s) does this change affect?**
Module(s): Guides
Week(s): N/A

**What is the work that needs to be done?**
I'd love some help moving the following pages from CYF Docs to our Curriculum. These might have dependency on us defining the assessment and milestone for SDC
- [Assessment](https://docs.codeyourfuture.io/leaders/running-the-course/assessment)
- [Milestones](https://docs.codeyourfuture.io/leaders/running-the-course/assessment/milestones)

**Why is this work important to do?**
It's important so we can have all our main guides and supportive tasks for our participants and trainees in one location: the curriculum

**Additional context**

**Who might need to know about this change?**
@SallyMcGrath @kfklein15  - I need to know so I can archive the CYF Docs page when done

**Comment by SallyMcGrath** [comment]
Archived
