### ISSUE TITLE
Not super clear what the intention is behind the "whole CSS course" prep in User Focused Data Sprint 1

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#937]
https://programming.codeyourfuture.io/user-data/sprints/1/prep/#css-skills-practice is an entire 19-video playlist totally about 2 hours.

It covers a lot of great material, but it's not super clear just navigating through the prep what the idea of what to do here is.

Are the trainees meant to just watch 2 hours of videos? Are they meant to do something with them? Are they meant to pick and choose some of the videos to specifically recap topics they're rusty on?

At the very least it would be handy to attach some learning objectives to this video playlist, but I'd also ideally like to see a narrative explaining _why_ they're watching them.

**Comment by SallyMcGrath** [comment]
I think this is leftover from HTML-CSS and I would drop it and the subsequent quiz, myself.

**Comment by SallyMcGrath** [comment]
moved and set to optional in #985

**Comment by illicitonion** [comment]
I still think a caption above/below this video saying "Optionally watch these videos to recap your knowledge of CSS - feel free to jump around or skip any topics you're confident on" or similar would be helpful...

**Comment by SallyMcGrath** [comment]
Obsoleted by #1241
