### ISSUE TITLE
Determine how solutions will be released to trainees

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#939]
https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/90 mentions that a task is "Review and refactor again once the coursework solutions are released."

I'm not sure we have a policy/plan around how we're going to release model/sample coursework solutions in ITP, given it's somewhat self-paced. Do we have a plan here? Is it written down somewhere so that volunteers know when/how they should be releasing solutions, and trainees know when/how this will happen or how to ask for it?

**Comment by SallyMcGrath** [comment]
I'm with @nbogie on this - solutions should be stored in a solutions branch on the repo and not locked or released.

It's pointless locking solutions given their VSCode can do all their homework for them in this course anyway.

**Comment by illicitonion** [comment]
We decided to just make public "solutions" branches.
