### ISSUE TITLE
"Identify components" prep has broken links

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#949]
https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/46 has two links that don't currently work

1. https://curriculum.codeyourfuture.io/html-css/sprints/4/prep/ no longer exists
2. https://cyf-workshops.netlify.app/components-1/docs/what-are-components.html no longer works, and _maybe_ should point at https://cyf-workshops.netlify.app/#components-1 ?

**Comment by SallyMcGrath** [comment]
updated the links

**Comment by illicitonion** [comment]
Thanks!
