### ISSUE TITLE
CLI Treasure Hunt has unclear submission instructions

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#951]
https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/71 says that "The submission clue is inside the treasure hunt."

I just did the exercise, and submission wasn't clear to me. I have ended up creating a file in a directory, but neither running a script which verified my solution was correct, nor run a script that told me what submitting I should be doing...

**Comment by illicitonion** [comment]
cc @SallyMcGrath

**Comment by SallyMcGrath** [comment]
Wow this is a blast from the past. Did we ask them to rickroll the class? I think it's from Zoomschool times

**Comment by illicitonion** [comment]
Yeah, this file has the last step (i.e. there's nowhere to go after this): https://github.com/CodeYourFuture/Project-CLI-Treasure-Hunt/blob/main/Clues/Who/clue.js and doesn't really conclude in a "submit this by ..." instruction.

**Comment by SallyMcGrath** [comment]
I guess let's have them make a cowsay and post it in Slack
