### ISSUE TITLE
Scrimba must be substituted

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/curriculum#956]
**Background**
[Scrimba](https://v2.scrimba.com/home) is the platform we used for one of our steps to learn HTML and CSS. However, they now have closed a lot of their access and are doing a lot of upselling which is confusing our ITD participants

**Acceptance criteria**
- Research alternatives for Scrimba
- Approve the substitute
- Create content for steps
- Ask @kfklein15 to update steps on Dashboard
- Update https://cyf-itd.netlify.app/steps/three/

**Comment by Ara225** [comment]
https://codeyourfuture.slack.com/archives/C07799JJD5E/p1725210385294379

**Comment by kfklein15** [comment]
German will try to get a free account. This will be a plan B ticket.

**Comment by kfklein15** [comment]
PR https://github.com/CodeYourFuture/curriculum/pull/1103

**Comment by SallyMcGrath** [comment]
Bumped, see #1103
