### ISSUE TITLE
Mermaid diagrams are blowing up 🔥 

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#96]
**Describe the bug**

I recently merged changes from `main` into the branches that contain the draft versions of JS1 ( e.g. `rewrite_js1_week-2` ). Following the merge, Mermaid diagrams are behaving weirdly: not rendering properly in the UI. They seem to be taking up loads of the page and there is a huge amount of whitespace between the parts of the diagram.

**What is wrong with the content?**

<img width="1567" alt="image" src="https://github.com/CodeYourFuture/curriculum/assets/25401570/41fc0878-7733-4531-a9a3-9232defaeb36">

**How could this be fixed?**
The only thing I could think of is some CSS is tampering with their layout but I couldn't track it down.

**Link to content**

[JS1 Week 2 deploy preview](https://deploy-preview-17--cyf-curriculum.netlify.app/js1/sprints/2/prep/)

**Additional context**

Mermaid diagrams normally throw when there is a syntax error so I think we can eliminate that possibility.
**Who else might need to know about this?**

**Comment by SallyMcGrath** [comment]
Oh that's an easy fix. I'll fix it now.

It's picking up height:100% from plain svg. But we also want some whitespace underneath these anyway, so we'll pop some inline styles right in the render hook

**Comment by SallyMcGrath** [comment]
<img width="1398" alt="Screenshot 2023-06-13 at 15 57 39" src="https://github.com/CodeYourFuture/curriculum/assets/42203406/a3687d10-0ff2-42b4-b8b3-bb2a8e6b3782">

**Comment by Dedekind561** [comment]
Awesome, thankyou! 👍
