### ISSUE TITLE
Tooltips can be hidden behind header

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#965]
On https://programming.codeyourfuture.io/structuring-data/sprints/1/prep/#playing-computer the top of the "playing computer" tooltip ends up behind the header:

<img width="1592" alt="Screenshot 2024-09-20 at 13 24 25" src="https://github.com/user-attachments/assets/b58b251e-c31d-4eed-83a6-3ed3f493f4e6">

We should probably bump the z-index of tooltips by a lot, as we generally want them to be displayed above _everything_.

**Comment by SallyMcGrath** [comment]
Hmmm, maybe? TBH futzing with layers like that just cascades in complexity.

I think maybe let's position it below instead of above the title
