### ISSUE TITLE
Check on reliability of Python Tutor

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#966]
https://github.com/CodeYourFuture/curriculum/blob/main/common-content/en/module/js1/playing-computer/index.md embeds an iframe from pythontutor.com which is currently reliably 504ing.

We should make sure pythontutor.com is still intended to work (and comes back up), and if not, find a replacement.

**Comment by FacuMa02** [comment]
Hi! I would like to collaborate in this issue.

**Comment by illicitonion** [comment]
Amazing, thanks @FacuMa02!

The main action item here is to see if the site is back up, and see if the visualiser on https://programming.codeyourfuture.io/structuring-data/sprints/1/prep/#playing-computer is working properly. If everything looks good there, we can close this issue and know we're happy. If the site is down, or the widget doesn't work any more, we can talk about what next steps we may need to take.

Thanks for your help!

**Comment by illicitonion** [comment]
It looks like Python Tutor is back and has been for a while - probably just a one-off blip :)
