### ISSUE TITLE
[Spike] Create a way to track code reviews

### ISSUE THREAD

**Issue by Ara225** [CodeYourFuture/curriculum#976]
Jay made a spreadsheet for the NW code reviews. The exact same concept wouldn't work for us but the idea of tracking stuff on a spreadsheet could work. we could either have people adding the links to the sheets directly or through agoogle form

The problem is giving feedback:
- volenteers could review them directly on the commits on Github(this is annoying on a number of levels and most devs don't know how to do this so friction)
- Volenteers could @ them in a Google sheets comment
- Volenteers could email them (I imagine this solution wouold make Sally sad because GPDR though)

None of these seem like good ideas. Of course something in the dashboard would be ideal  - maybe we could make the code review directly part of the process, using comments to provide the code review. Maybe that wouldn;t even need any changes

**Acceptance criteria**
- Identify any requirements needed by ITD on the PR review logic on [this repository](https://github.com/CodeYourFuture/coursework-apps-script)

**Comment by AmyCYF** [comment]
@Ara225 I think this is worth bringing up in the Retro on Monday

**Comment by SallyMcGrath** [comment]
I think it might make more sense to remove the code review step. What do you think @cjyuan ?

**Comment by cjyuan** [comment]
I support removing the code review step.

We can use A/C to let both participants and volunteers know exactly what to expect. For example, to ensure there is no error in the HTML/CSS code with the help of a validator. This way, volunteers can just check if participant's webpage meets the A/C and give feedbacks accordingly on Dashboard (which is kind like a code review).

Doing so can save volunteers a lot of time from tracking code review requests on Slack.

**Comment by Ara225** [comment]
We agreed at the meeting that step 4 will die because of the Scrimba replacement. Are we happy to close this ticket?

**Comment by cjyuan** [comment]
I think we will be replacing (CYF blocks) by a modified version of step 4. In any case, there won't be a separate reviewing step on Slack. So we can close this ticket.
