### ISSUE TITLE
Wrong link in M1 S3 backlog check module success criteria

### ISSUE THREAD

**Issue by fcaroline2020** [CodeYourFuture/curriculum#980]
**Describe the bug**

Under the backlog task 🧑🏾‍⚖️ Check module success criteria 

The link takes you to 404 not found

https://curriculum.codeyourfuture.io/html-css/success/

The correct link is on the issue:
https://programming.codeyourfuture.io/user-data/success/

**What is wrong with this content?**

**How could this be fixed?**
Link needs to be updated

**Link to content**
https://programming.codeyourfuture.io/user-data/sprints/3/backlog/

**Additional context**

**Who else might need to know about this?**

**Comment by SallyMcGrath** [comment]
this seems like someone edited it already
