### ISSUE TITLE
ITP Build is failing

### ISSUE THREAD

**Issue by sampennington** [CodeYourFuture/curriculum#990]
**Describe the bug**
ITP builds are failing, there is a broken link in the common docs. 

`<urls.Parse>: error calling Parse: parse "\"https://codeyourfuture.io/\"": first path segment in URL cannot contain colon`

Example run: https://github.com/CodeYourFuture/curriculum/runs/30567499057

**What is wrong with this content?**

**How could this be fixed?**

**Link to content**

**Additional context**

**Who else might need to know about this?**

**Comment by illicitonion** [comment]
Suspect this was https://github.com/CodeYourFuture/curriculum/pull/974 - @SallyMcGrath

**Comment by SallyMcGrath** [comment]
> Suspect this was #974 - @SallyMcGrath

Yeah, I fixed it #991  - if you can merge that would be great
